### ISSUE TITLE
milestones

### ISSUE THREAD

**Issue by ImmanuelSamuel** [playcanvas/engine#1002]
I would be nice if there were milestones created here so users can see ongoing development and planned features.

**Comment by willeastcott** [comment]
GitHub describes milestones as follows:

"Use Milestones to create collections of Issues and Pull Requests for a particular release or project."

As you have probably noticed, we generate releases a lot faster than many other open source projects. It's not uncommon for us to have multiple releases of the engine per week. And our engine 'projects' tend to be delivered by one engineer per 'project' in a single PR. So GitHub's milestones feature doesn't map very well onto the PlayCanvas engine repo.

To see ongoing development, just keep an eye on the master branch and the list of incoming PRs.

Now, I do think we should start publishing a roadmap, which may be more what you're after. I'll have a think about the best way to do that. But for now, I'm going to close this issue because we don't have plans to start generating milestones on GitHub, at least for the moment.

**Comment by highvrahos** [comment]
@willeastcott a roadmap would be more than welcome!
