### ISSUE TITLE
Wireframe data wrong on complex model

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#1045]
Here is a [demo project](https://playcanvas.com/editor/scene/569334), using 100k and 200k vertices models.
Go to launch page and then you can see the result.

Screenshot:

![image](https://user-images.githubusercontent.com/2386165/33307795-d7e34d50-d452-11e7-808c-01feed7392cf.png)

![image](https://user-images.githubusercontent.com/2386165/33307826-fd2d29fa-d452-11e7-9b7e-9f6a7c559976.png)

**Comment by willeastcott** [comment]
This is because of this line:

https://github.com/playcanvas/engine/blob/master/src/scene/model.js#L259

We force 16-bit indices for wireframe meshes. And you're getting int overflow with your model because it has >65535 vertices. @guycalledfrank - we could just switch to 32-bit when necessary, but there is only about 95% support for 32-bit indices in WebGL 1. The correct approach would be to generate more than one mesh maybe?

**Comment by guycalledfrank** [comment]
We already use 32-bit indices for models that don't fit into 16. So perhaps switching to 32 in generateWireframe would be consistent?

**Comment by willeastcott** [comment]
Except 32-bit index support is not guaranteed for WebGL 1.0. I believe support is around 96% or something, although webglstats.com is down at the moment so I can't verify.

**Comment by slimbuck** [comment]
This should be fixed in #2023
