### ISSUE TITLE
VR-mode apps super sensitive to motion

### ISSUE THREAD

**Issue by tomkuipers** [playcanvas/engine#1219]
On Chrome m66 on Android the camera is super sensitive to motion. The camera jumps around like crazy. Try for example the “WebVR Lab” project with Chrome on an Android device:
https://playcanvas.com/project/446331/overview/webvr-lab

The issue is not unique to PlayCanvas: it’s also reported for Aframe. See for example: https://github.com/aframevr/aframe/issues/34761
Video illustrating the issue: https://vimeo.com/260723899

Root of the problem is that DeviceMotionEvent.rotationRate units have changed from degrees per second to radians on Chrome m66.

This has been going on for months now. Has nobody else experienced this problem?
Any solutions?

**Comment by willeastcott** [comment]
This is because PlayCanvas has a hard dependency on an old version of the WebVRPolyfill. 

We're removing the dependency on the WebVRPolyfill from the engine:

https://github.com/playcanvas/engine/pull/1648

Soon, you'll optionally be able to include it yourself in your projects (and be able to select whichever version you want). Therefore, I'm closing this. 

This will resolve this mishandling of device motion data.
