### ISSUE TITLE
setGravity throwing errors

### ISSUE THREAD

**Issue by muit** [playcanvas/engine#137]
The line ``` application.context.systems.rigidbody.setGravity(0,-9.8,0);``` returns:
```Uncaught TypeError: Cannot read property 'setValue' of undefined```
where "undefined" is "this._ammoGravity"

playcanvas.js:17223: 
```this._ammoGravity.setValue(x, y, z);```

PlayCanvas version: 0.162.5

**Comment by willeastcott** [comment]
If you are an engine user, this is because you are no included ammo.js into your page:

`<script src="http://code.playcanvas.com/ammo.751ec5f.js">`

For example, see [this example](http://codepen.io/playcanvas/pen/ctxoD).

If you are using the [PlayCanvas cloud editor](https://playcanvas.com/), it's because you don't have 3D Physics turned on. Go to the project settings page for your project and ensure the 'Enable 3D Physics' option is checked. We are aware of a bug where this can become unset - we will fix this very soon.

**Comment by muit** [comment]
Wow, I didn´t see that. Thanks!
