### ISSUE TITLE
Parameters of material are not cloned (anymore)

### ISSUE THREAD

**Issue by MrTelanie** [playcanvas/engine#1514]
### Description

I am quite its a newer bug, in past I could clone materials with parameters, which I need for shaders.
The current implementation does not seem to try to clone parameter anyway.

Is this a bug, or a feature?

### Steps to Reproduce

1.  `orgMaterial.setParameter('hello', 1);`
2. `orgMaterial.getParameter('hello') -> 1`
3. `newMaterial = orgMaterial.clone();`
4. `newMaterial.getParameter('hello') -> undefined`

### Workaround

sorry, removed workaround code, did not work

out of this workaround, I can try to make a fix, but first I must find out, if its expected behavior.

Greetings.

**Comment by Glidias** [comment]
It was available last time? What was the reason it might be gone/removed?

I think part of the consideration is whether cloning parameters should be shallow vs deep copy. Obviously, this depends on your use case where deep copying might be beneficial vs shallow copying. Which convention is better? I dunno. 

If parameters don't get cloned automatically, it must be done manually or via a seperate helper function. Can playcanvas team confirm that parameters aren't meant to get cloned with clone() function? I think material management is one thing many advanced users will handle manually since use cases can be different. (eg. replacing all batches with the same material without even using the cloned materials if they need to be all updated at once with the same parameters, or sharing the same parameters object, eg.)

**Comment by MrTelanie** [comment]
my current work around is quite similar.
instead of using entity.clone() i clone my hand all meshes and materials.

i think what i would need is a "material-script" like a normal script is for entity, but for material.
reusing this would be much simpler :)

thanks for the feedback
