### ISSUE TITLE
Factor out calls to getProgramParameter and getActiveAttrib

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#154]
These calls are slow. See the pc.Shader constructor. We can probably figure out ahead of time how many attributes and uniforms there are and know their names to get their locations.

**Comment by Maksims** [comment]
After some research, those calls itself are not really slow.
WebGL has underlying thread with queue of commands. This queue is executing independently.
Once page thread (JS) needs some data from webgl, for example status of shader compilation, or parameter location, then it makes those requests, webgl thread checks if program or shader that data is required from is available (finished compilation), if it is not, then it has to block main page JS thread, wait till WebGL thread queue comes to the point it can execute commands gl command, get result and throw back to page js thread, unpausing it.
That basically leads to the thread lock.

There are two approaches can be taken, first one would require some research done, in order to identify which of the webgl commands do block, and if they are avoidable by any chance. If they are - then we all great, and can just have it as it, without using those commands.

Another approach would be alternative option, only should be considered if first approach is not possible.
That would require engine to predict how long program would take to compile, then create small timeout before executing blocking webgl commands. That would allow page thread execute js, do some other things, before shader will be created.
It creates two main considerations - shader creation will become async, and might involve some considerations for developer, but I believe it is simple and common async approach.
Second consideration is amount of time to wait till executing blocking wegbl commands, as there is nothing clearly indicates how long it will take, and there seems to be no easy way to check if it is done or not without blocking. So that would require some research and try.

But at the end we might have nice async shader creation without any blocks, that will greatly improve responsiveness of javascript and preventing page js thread to be blocked.

**Comment by willeastcott** [comment]
I'm going to close this because we did some work to delay shader linking in the engine. The only other things we can do are start compilation earlier or reduce the number of shaders generated (probably by moving to deferred rendering). These should be opened as new issues IMHO. The original premise of the bug report was wrong.

**Comment by Maksims** [comment]
Although few improvements we still missing: start compilation during loading of assets using placeholder textures to prevent recompilation on texture availability.
As well as think of alternative ways to get parameters from compiled shader, as there might be cheaper options.
