### ISSUE TITLE
pc.PostEffectQueue does not leverage MSAA in offscreen render targets

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1572]
WebGL 1 does not support MSAA for offscreen render targets (FBOs). This means that when you use post effects on WebGL 1 devices, you would need to apply a post effect to implement some form of AA (like FXAA, say) if you want it.

WebGL 2 does support this however.

If you use any of the example post effects in PlayCanvas on a WebGL 2 capable device, you lose antialiasing. The engine does have a function which supports the copying of an MSAA render target to the back buffer. 

https://github.com/playcanvas/engine/blob/master/src/graphics/device.js#L1006

But the pc.PostEffectQueue system does not use this function. We should update it to use the copy function when WebGL 2 is available.

**Comment by Maksims** [comment]
I had to add MSAA to some post-effect, and simply overridden `_createOffscreenTarget` method on `PostEffectQueue.prototype`.
Adding `samples` option to params object on this line: 
```javascript
return new pc.RenderTarget(this.app.graphicsDevice, colorBuffer, { depth: useDepth, stencil: useStencil, samples: 4 });
```
https://github.com/playcanvas/engine/blob/master/src/framework/components/camera/post-effect-queue.js#L74

Does the trick. So good API needs to be figured out.

**Comment by c0debon** [comment]
As Maksims says, the issue is not that an incorrect version of copy is used when copying out the backbuffer. Instead what's happening is the first post effect in the chain actually creates a render target that the camera then uses for rendering the scene. Currently the target is never created with multisampling.

The flow seems a little odd to me. I would have expected the engine to render to the back buffer as usual and then at post effect time, copy out the resulting image and continue.

The most straightforward fix for now would be to match the first post effect's render target samples to match the backbuffer setup.

**Comment by willeastcott** [comment]
@c0debon In WebGL 1, the only way to copy out the back buffer is with gl.readPixels which is very slow and stalls the graphics pipeline ([this](https://stackoverflow.com/questions/28282935/working-around-webgl-readpixels-being-slow) is a good read). WebGL 2 has a blitFramebuffer function which is fast:

https://github.com/playcanvas/engine/blob/master/src/graphics/render-target.js#L162
