### ISSUE TITLE
pc.Mesh does not support more than one vertex buffer

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#163]
You can't currently assign more than one vertex buffer to a pc.Mesh. This means that you can't, for example, have certain attributes (say normals and uvs) in a static buffer and other attributes (maybe positions) in a dynamic buffer that are updated every frame.

**Comment by Maksims** [comment]
Is this still a problem or consideration for future updates? Please give some feedback on this @willeastcott @guycalledfrank 
Otherwise this ticket shall be closed due to lack of activity.

**Comment by guycalledfrank** [comment]
I'm not sure we need such low-level features to be user-driven. Besides it would complicate every single mesh processing algorithm in the engine.

**Comment by Maksims** [comment]
Shall we close on this ticket then?

**Comment by willeastcott** [comment]
glTF vertex data is loaded via ArrayBuffer from .bin files. Ideally, you want to point a pc.VertexBuffer at this data and use it directly without having to copy it. This is fine if the glTF vertex data is interleaved. But the most common layout for the vertex data is non-interleaved. This means we'd need to create a pc.VertexBuffer per attribute, presumably. And a pc.Mesh would need multiple pc.VertexBuffer objects.

**Comment by mvaligursky** [comment]
I think we should not implement this. My reasons:
- we already have internal support for multiple vertex buffers, used by instancing and morphing. This works well for cases this is really needed.
- I don't think we need to expose this as a public API due to small benefits for added complexity.
- the case of using GLB vertex data in place - if vertex data is not-interleaved, it's very fast to memcopy that data to non-interleaved vertex format buffer, and thus avoiding cost of interleaving. I think this would be the preferred solution to adding multi VB complexity.

**Comment by willeastcott** [comment]
OK, let's close then.
