### ISSUE TITLE
Cubemap quality bug in IE11

### ISSUE THREAD

**Issue by bibrick** [playcanvas/engine#1798]
This article what i wrote on forum
https://forum.playcanvas.com/t/ie11-webgl1-cubemap-is-strange-engine/11683/3

### Description
I’ve just tried setting on cubemap (engine code).
It works fine on chrome and Edge browsers but it doesn’t work as my expectation in IE 11.

* URL to a simple, reproducible test case.
https://github.com/velbi/cubemap-test

* Screenshots
* Edge
![cp1](https://user-images.githubusercontent.com/39391128/71654314-64deca00-2d74-11ea-9ba3-63313282d77c.png)

* Chrome
![cp2](https://user-images.githubusercontent.com/39391128/71654316-69a37e00-2d74-11ea-9b0e-6caf7c146b76.png)

* Internet Explorer 11
![cp3](https://user-images.githubusercontent.com/39391128/71654321-745e1300-2d74-11ea-8bc9-323805088925.png)

### Steps to Reproduce

1. Clone https://github.com/velbi/cubemap-test 
2. Add some server (I just use yarn add live-server)

**Comment by willeastcott** [comment]
I believe this is because your app has `app.scene.skyboxMip` set to `0`. In this case, the skybox is rendered using the PNG cubemap faces (whereas if `app.scene.skyboxMip` is set to `1` or more, it uses the DDS image data). IE11 has a bug where it will premultiply the RGB data by A and then it is divided away when the texture is used and this causes precision loss and hence the banding. Hey, @slimbuck - did I get that right? Is it worth keeping this issue open (since it's not technically a PlayCanvas bug). Or do you hope we can devise a workaround to this where we no longer rely on PNG format for holding RGBM data?

**Comment by slimbuck** [comment]
That's exactly right @willeastcott. I think it's worth keeping this ticket around because it this this also still a problem on iOS and we should find a workaround.

**Comment by willeastcott** [comment]
The new RGBP format (introduced by @slimbuck) should resolve this. Also, the iOS issue @slimbuck references above is now resolved (see #1930). Plus, with the vanishingly small userbase of IE11 these days, I'm closing this.
