### ISSUE TITLE
AssetsRegistry, prefix with url caching inconsistencies

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#1813]
There is a prefix feature in AssetsRegistry. When loading assets, it is mostly respected, but there are some areas where it is not respected well, leading to issues. For example, we [cache list of loaded assets by URLs not respecting prefix](https://github.com/playcanvas/engine/blob/master/src/asset/asset-registry.js#L196-L197). And it does not respect variants as well. Then when we load model, we load materials from mappings, and [trying to retrieve material from index](https://github.com/playcanvas/engine/blob/master/src/resources/model.js#L127-L130), which uses getFileUrl, which then respects [variants](https://github.com/playcanvas/engine/blob/master/src/asset/asset.js#L168) and adds [prefix](https://github.com/playcanvas/engine/blob/master/src/asset/asset.js#L175-L176).
So it will never work, once prefix is set to anything.

**Question:** Do we add prefix into cache keys, and ensure we subscribe to full paths with prefixes (as is now).
Or do we change the way we try to retrieve asset from that cache, by making url without prefix to match current cache keys?

**Comment by slimbuck** [comment]
@Maksims I agree this is an important issue. I have no solutions, just confirming my support that we should address this.

On a related note, I have started wondering whether it might be helpful to make asset.file something concrete and public (instead of what it currently is - an untyped internal detail of asset).

This way we could introduce a standard method for, say getting cache keys while still allowing users to customize the behavior. Asset.getFileUrl() could be a member and also Asset.getPreferredFile() and variants too.
