### ISSUE TITLE
Importing .OBJs without normals

### ISSUE THREAD

**Issue by digital-chef-info** [playcanvas/engine#1815]
I am using the obj-model parser script to import my models (https://github.com/playcanvas/engine/blob/245afc498fd3e189f6166c6b060a6443e65cf0b9/examples/assets/scripts/loaders/obj-model.js). 
Unfortunately most of my models are not exported with normals and this script does not add them either. This results in the following: 
![image](https://user-images.githubusercontent.com/52910305/72324494-616c0c80-36ab-11ea-81a8-d74ed271e4ff.png) (left is imported on runtime - right is imported via the editor)

We have added pc.calculateNormals in the obj-model parser but it seems like the generated normals are 'flat': 
![image](https://user-images.githubusercontent.com/52910305/72324626-ac861f80-36ab-11ea-977b-ce7599aef932.png)

Modified snippet of the parser:
```javascript
var model = new pc.Model();
var groupNames = Object.keys(parsed);
var root = new pc.GraphNode();
// create a new mesh instance for each "group"
for (i = 0; i < groupNames.length; i++) {
    var currentGroup = parsed[groupNames[i]];
    if (!currentGroup.verts.length) continue;
    if (currentGroup.verts.length > 65535) {
        console.warn("Warning: mesh with more than 65535 vertices");
    }
    var indices = currentGroup.verts.map(function (x, i) { return i; }); // (((i/3)|0)*3)+[0,1,2][(i%3)]
    var norms = pc.calculateNormals(currentGroup.verts, indices); // generate normals
    var mesh = pc.createMesh(this._device, currentGroup.verts, {
        normals: norms,
        uvs: currentGroup.uvs
    });
    var mi = new pc.MeshInstance(new pc.GraphNode(), mesh, this._defaultMaterial);
    model.meshInstances.push(mi);
    root.addChild(mi.node);
}
model.graph = root;
model.getGraph().syncHierarchy();
return model;
```

I was hoping someone else could look at this and possibly help resolve this.

**Comment by mvaligursky** [comment]
I had a quick look at calculateNormals function, and that averages vertex normals from faces using the same vertex.
It seems the model it works on does not have vertices shared by faces - each vertex should be used by multiple triangles, but instead of each vertex is only used by a single triangle.

And I just had a look at the parser you're using - and that's exactly what it does. The known issue comment says: - doesn't created indexed geometry
Which means vertices are not shared (that needs index geometry).

You could ether find parser which handles that, or update current one I think.

**Comment by mvaligursky** [comment]
perhaps try obj loader from this project
https://playcanvas.com/project/503071/overview/obj-loader 
it seems to create index buffer as well

**Comment by mvaligursky** [comment]
I'll close this one as no work is needed to be done for the engine, see comments above.
