### ISSUE TITLE
Engine - Sprites can't be seen in Safari Browser in Mac

### ISSUE THREAD

**Issue by ConchisAE** [playcanvas/engine#1826]
I used play canvas to create a demo so my buyers can see how the aumented reality animation of the shirt they are viewing works. The only problem is that, when the build is opened in Safari in a Mac, the sprites look as if they had only the alpha but instead of in white, in black. As soon as you open the build in safari, you can see the error.

This is one of the builds that has that problem: 
https://playcanv.as/p/5ce7fKKs/

**Comment by slimbuck** [comment]
Hi @ConchisAE,

I can reproduce the issue in Safari so I used the texture in a test scene and it seems to work fine, see https://playcanv.as/b/celJEqQj/ so must be something specific to your project.

Please can you give me access to your project so I can take a look?

Thanks

**Comment by ConchisAE** [comment]
Sure, can you please tell me how to do that? 
Thanks in advance slimbuck

**Comment by slimbuck** [comment]
Sure - go to the settings dashboard (the page with the 'EDITOR' button at the top) where you can change the project name etc, click settings. Then on the right of the page you can add me, slimbuck.

**Comment by ConchisAE** [comment]
Oki doki, Slimbuck, i already added you with "Read" allowance, Is this ok? do you need me to change it?

**Comment by slimbuck** [comment]
I can't actually reproduce this issue unless I run the two published builds in the project you shared.

This means I can't confirm unfortunately, but think this issue is related to a known bug in Safari browser on macos. We have a workaround for Playcanvas which should be released soon, see https://github.com/playcanvas/engine/pull/1839.

Please will get you get the next engine release once it's out and test with that?

Thanks!

**Comment by slimbuck** [comment]
Closing for now. If the next engine release doesn't address this issue, please reopen.

**Comment by ConchisAE** [comment]
oki doki Slimbuck, I will try it out and inform you the results, thanks for all your help :D
