### ISSUE TITLE
`ScriptType` Typescript typing is being used for both script types and their instances?

### ISSUE THREAD

**Issue by TheJonRobinson** [playcanvas/engine#1889]
### Description

We have some code that wants to access a script's attributes from it's instance, which all looks fine from the typings. This is to support some runtime introspection. Elsewhere, `pc.createScript` is used to get a script type and set its attributes up. However, when trying to do the former, the types are 'wrong' (the instance's `attributes` should be static).

I think the problem stems from `ScriptType` trying to do double-duty:
- As the `ScriptType` returned from `pc.createScript()` in order to define attributes etc.
- ALSO as the `ScriptType` returned from `pc.ScriptComponent.scripts` - i.e. the script instances.

I guess we've been avoiding hitting this because we only used attributes in the `createScript` case. As it stands though, it 'appears' like we can type-safely read attributes from an instance, but at runtime they're not present in the physical object as instance member (but are as static ones).

**Comment by Maksims** [comment]
To clarify, there is a Function and an Object (can be created by function).
ScriptType - is just an abstract term, in reality [pc.createScript](https://github.com/playcanvas/engine/blob/master/src/script/script.js#L297-L623) simply defines new Function and returns it.
It is almost same as you would instead of this:
```javascript
var MyScript = pc.createScript('myScript');
```
Do this:
```javascript
var MyScript = function () { };
```

`createScript` defines a lot of stuff and defines new function to be extended and used by developer.
It as well adds `attributes` property to that function, so developer can define new attributes.

Then, when you use that script on script component, it creates objects (instances) using that function, simply speaking this: `new MyFunction()`. And entity.scripts - has list of instances, not functions.

ECMA5 does not have classes, it has functions with prototypes. Although ECMA6 adds classes, which makes it easier to understand.

From the source, you can see, that there are [some properties defined](https://github.com/playcanvas/engine/blob/master/src/script/script.js#L361-L363) on script instances, which you could access to iterate through attributes.

**Comment by TheJonRobinson** [comment]
Thanks for the clear explanation - I should have been clearer that this is a Typescript typing issue (title updated).

For the createScript scenario in Typescript:

```
    const script: pc.ScriptType = pc.createScript(scriptName);
    script.attributes...; // Fine
    script.extend...; // Error: property 'extend' is a static member of type 'ScriptType' 
```

The types say that my newly created script has `attributes`. As a side issue, the typings also disallow `extend`.

In the script instance scenario:
```
        const scripts: pc.ScriptType[] = entity.script.scripts;
        for (const script of scripts) {
            script.attributes... // This is allowed at compile time but is undefined at runtime
```

Ideally for Typescript type-safety we want the typings to be correct and prevent incorrect use. 

Although we can spy into the source to see underlying __implementations, I would argue this is not a sustainable approach for JS or TS users, as the norm here is that undocumented underpinnings are subject to change as needs be by the writers. In the case of Typescript, we would need to 'cast away' the type to get to the guts, which is something to be avoided when trying to strongly type.

**Comment by willeastcott** [comment]
I believe that #1908 fixed this. Can you confirm @TheJonRobinson?

**Comment by TheJonRobinson** [comment]
Awesome! I'll take a look ASAP

**Comment by TheJonRobinson** [comment]
Hi Will - we integrated this but Al found that `pc.registerScript` seems to have gone from the types. Are we missing something?

**Comment by willeastcott** [comment]
@TheJonRobinson Have you tried creating a new folder, cd-ing into it and typing `npm install playcanvas'. Then, open the downloaded `playcanvas.d.ts` and search for `registerScript`. What do you find?

**Comment by TheJonRobinson** [comment]
Okay - it is present there, so maybe we're being dumb. I'll get back when I chat to Al on our team who was making the changes.

**Comment by TheJonRobinson** [comment]
So this does seem to be working barring a type which I notice you guys fixed here: https://github.com/playcanvas/engine/commit/4c920344cb866f5024750cf1de5383267781f583

**Comment by TheJonRobinson** [comment]
Ah @willeastcott we realised we hadn't tested the Parse flow, and this doesn't seem to work for us.

When I copy the sample `class CameraController...` from https://github.com/playcanvas/engine/pull/1908 I get a 'cannot read property attribute of undefined' exception. We get the same with our own attempts using Typescript, but it looks like the ES6 part is the problem before we get to Typescript.

**Comment by willeastcott** [comment]
Hi @TheJonRobinson - can you remind me where things are at with this issue. Me and my bad memory. 😄

**Comment by TheJonRobinson** [comment]
Hi Will - I was looking at this at the weekend. We've had some other semi-related issues which slowed me down (I'll open a separate issue) but this is looking good now so I'll close. Thanks!
