### ISSUE TITLE
ASTC compression for .hdr, .exr lightmap texture

### ISSUE THREAD

**Issue by TrongHieu90** [playcanvas/engine#1959]
Hi,
I just read this article and it seems to be a decent way to compress the hdr lightmap texture, since this one takes the most chunk out of vram.

https://community.arm.com/developer/tools-software/graphics/b/blog/posts/high-quality-rgbm-texture-compression-with-astc

And ASTC seems to work with android browser side at at least.
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_astc

**Comment by slimbuck** [comment]
Hi @TrongHieu90,

Not too long ago we added basis compression support to the playcanvas engine. Basis is a 'supercompressed' format and so a single basis texture transcodes at runtime to any of the target compression formats (atc, astc, etc1, etc). This simplifies the asset pipeline considerably since you need just one texture to support all target platforms, instead of multiple versions of a texture in different compressed formats.

Up to now basis has internally only supported cut-down ETC1 compression and has struggled in some situations with quality issues. The developers recently added the option of UASTC internal format which promises better quality (with possible size tradeoff).

We haven't had a chance to merge in the UASTC format yet, but hopefully soon.

Anyhow, if you're interested you can get more info at https://github.com/BinomialLLC/basis_universal.

**Comment by willeastcott** [comment]
Closing since the engine now supports ASTC compression as a transcode target for Basis, plus an encoding format for Basis textures. Please reopen if there are any other outstanding ASTC-related questions.
