### ISSUE TITLE
UI button component bug when removing from list

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#1996]
I have an element group in 2D Screen. Each child has a button, that allows it to remove itself from the list. I simply destroy the list and re-populate it with the new list, excluding the removed element.

The problem happens when the `.destroy()` method is called. I have made [a sample project](https://playcanvas.com/editor/scene/904854) to demonstrate the issue.

**Comment by yaustar** [comment]
Error when clicking on the button:

```
playcanvas.dbg.js?version=1.51.4:43575 Uncaught TypeError: Cannot read properties of null (reading 'active')
    at ButtonComponent.get (playcanvas.dbg.js?version=1.51.4:43575)
    at ButtonComponent._determineVisualState (playcanvas.dbg.js?version=1.51.4:49399)
    at ButtonComponent._updateVisualState (playcanvas.dbg.js?version=1.51.4:49329)
    at ButtonComponent._onMouseUp (playcanvas.dbg.js?version=1.51.4:49237)
    at ElementComponent.fire (playcanvas.dbg.js?version=1.51.4:758)
    at ElementInput._fireEvent (playcanvas.dbg.js?version=1.51.4:75357)
    at ElementInput._onElementMouseEvent (playcanvas.dbg.js?version=1.51.4:75219)
    at ElementInput._handleUp (playcanvas.dbg.js?version=1.51.4:75044)
```

**Comment by jpauloruschel** [comment]
As a separate issue I came across while testing the fix I explained in my earlier comment, I noticed that the `Button`s and `Element`s were not responding properly to all events: they were responding to `click`, but not to `hover`, so they were interactable but the "hover tint" animation was not working. The quick fix for that is to  set `enabled = true` *after* it is added to the hierarchy:

```
// instead of:
  ...
  entry.enabled = true;
  this.group.addChild(entry);
}

// do this:
  ...
  this.group.addChild(entry);
  entry.enabled = true;
}
```

I think this needs a new investigation.

**Comment by LeXXik** [comment]
That was a good investigation! Thank you for looking into it, @jpauloruschel !

**Comment by jpauloruschel** [comment]
About the `enabled` and `addChild` order issue:

## The Issue

The issue is around the entity linking on `Button.imageReference`, which uses an `EntityReference`. The `imageReference` property on the `Button` is actually just a `guid` (string). Then, whenever it is needed, the `EntityReference` class is used to actually resolve that `guid` to the scene `Entity` - but, in order to do that, the entity *needs* to be in the scene graph for it to be found: https://github.com/playcanvas/engine/blob/dcbfd71c36e6ee1b1adbaa3d4c8a12fdcf0f159d/src/framework/utils/entity-reference.js#L259-L273

(in the code above, look at line 272: if the Entity is not in the Graph (descendent of root), the reference is set to `null`).

If you do
```
entity.enabled = true;
parent.addChild(entity);
```
the EntityReference will not be able to find the target entity on enabled call - because it wasn't added to the graph yet. However, if you do
```
parent.addChild(entity);
entity.enabled = true;
```
the `enabled` call will notify the `EntityReference` to update the reference, and this time it will find it - because it was already added to the scene graph.

Note that there is also a path between `addChild` and the `EntityReference._updateEntityReference`, but it is only called if the enabled state has changed: https://github.com/playcanvas/engine/blob/dcbfd71c36e6ee1b1adbaa3d4c8a12fdcf0f159d/src/scene/graph-node.js#L1270-L1278
on the case above that it doesn't work, both sides of the `if` statement are `true`, so `_notifyHierarchyStateChanged ` is not called.

## An idea to solve it

To solve this, I propose the following change to `EntityReference`:
```
if (nextEntityGuid) {
    const root = this._parentComponent.system.app.root;
    const isOnSceneGraph = this._parentComponent.entity.isDescendantOf(root);

    if (isOnSceneGraph) {
        nextEntity = root.findByGuid(nextEntityGuid);
    } else {
        // if the entity is not in the scene hierarchy, try to find the referenced entity as a child of it
        nextEntity = this._parentComponent.entity.findByGuid(nextEntityGuid);
    }
}
```
