### ISSUE TITLE
Draco compression texture issue

### ISSUE THREAD

**Issue by absconcept** [playcanvas/engine#2052]
### Description

Loading a model from Blender gLTF that does not have DRACO compression works fine, but doing the same with DRACO gLTF enabled, the textures are missing. The 3D Draco file loads fine in other WebGL viewers.

* Download the 3D test file with DRACO from [here](https://www.dropbox.com/s/6qg6bl0wcexzhpl/cscanv5-PlayCanvas-DRACO.gltf?dl=0)

* file loaded on gltfEditor.com
![With DRACO compression on gltfEditor-com](https://user-images.githubusercontent.com/35725556/81144265-fbfe9d00-8f73-11ea-941f-0ca35f585960.jpg)

file loaded on Playcanvas online viewer
![With DRACO compression on playcanvas](https://user-images.githubusercontent.com/35725556/81144272-fdc86080-8f73-11ea-854b-f5f992ca9823.jpg)

* A screenshot of http://webglreport.com/ (for graphics related issues)
![Annotation 2020-05-05 204202](https://user-images.githubusercontent.com/35725556/81103172-f754cd00-8f10-11ea-9653-6f5fcfef3463.jpg)

**Comment by slimbuck** [comment]
Looks like this was tested with playcanvas-gltf, but engine support also fails with the following errors:

![Screen Shot 2020-05-06 at 9 18 34 AM](https://user-images.githubusercontent.com/11276292/81153408-ce692200-8f7a-11ea-8171-6284d98935eb.png)

**Comment by mvaligursky** [comment]
Hi @absconcept,

Thanks for creating this report. It seems you are using the old glb viewer from playcanvas, and not the new one we are actively developing at the moment. The reason is perhaps that it's not published on web yet, and you need to host it yourself. If you are keen, please use this till we publish it: https://github.com/playcanvas/engine/tree/master/tools/glb-viewer
You need to host engine folder, and point it to this folder.

But new glb viewer does not load your draco compressed mesh either. I tried loading it using both babylon js and three js viewers, and they do not display it correctly either. 

https://gltf-viewer.donmccurdy.com/
https://sandbox.babylonjs.com/

I also tried to validate it using glb validator (https://github.khronos.org/glTF-Validator/) and that reports 5 errors of this type:
`"code": "MESH_PRIMITIVE_TOO_FEW_TEXCOORDS",
                "message": "Material is incompatible with mesh primitive: Texture binding '/materials/2/pbrMetallicRoughness/baseColorTexture' needs 'TEXCOORD_1' attribute."` 

So it does feel there is some issue with the file, that perhaps gltfEditor.com is somehow working around.

Perhaps try one of these tools to convert your source mesh to draco compressed glb:
https://github.com/CesiumGS/gltf-pipeline
https://github.com/facebookincubator/FBX2glTF

If you have source fbx file for this, or gltf that loads in our and other viewers, I could give this a try as well.

Thanks
Martin

**Comment by absconcept** [comment]
Hi Martin,

Here is a None DRACO version that works fine in your viewer,
https://www.dropbox.com/s/sl58doerc1qu4zl/cscanv5-PlayCanvas-NONE-DRACO.gltf?dl=0

I hope this helps, we just find it odd, why the none DRACO works ok, but the DRACO one has issues.

Abs

**Comment by mvaligursky** [comment]
It seems there could be an issue in gltfEditor when draco compressing meshes. Your draco file for reference is 6MB large.

I used gltf pipeline to compress it
`gltf-pipeline -i cscanv5-PlayCanvas-NONE-DRACO.gltf -o draco.glb -d -b`
the created file is 2.4MB and works correctly in our new viewer (not the old one), and also third party viewers.

I also used https://gltf.insimo.com/
the created file is 2.1MB and again works in the new viewer (and not old one).
The tool is little strange to use .. but this is what I did: 
1. go to https://gltf.insimo.com/
2. click on Open and load your gltf
3. Click on tools, then click on Draco compression .. few seconds later it gives you compression result log. 
4. Then click on Pack GLB .. and wait for log report again.
5. Click on Save, and download draco compressed glb.
But sometimes file is too large and needs clicking around on Draco / Pack GLB few times for it to work .. 

Conclusion:
1. Use our new viewer (and not https://playcanvas.github.io/playcanvas-gltf/viewer) to view glb, that's new and supported and better version.
2. Use gltf-pipeline to draco compress your files, that one is reliable.

**Comment by absconcept** [comment]
Ah, ok think I need to use the gltf-pipline, as the Blender DRACO export is the problem here, see the video recording:

https://drive.google.com/file/d/1RID8xiDJs0UiR-M1RsZnpZgvRiIob_Q3/view

**Comment by absconcept** [comment]
Hi, your ../../build/output/playcanvas.js is missing, as such we can not get the New player to work. please advice?

**Comment by mvaligursky** [comment]
if you want to run this locally, before we publish it, you should get code of the engine (clone git repo or download it) from here: https://github.com/playcanvas/engine
And then Follow the "How to build" section to build a local version of the engine - which generates that playcanvas.js file.

We are looking at publishing the new fewer soon, so another option could be to wait for this. Perhaps @willeastcott can suggest other options?

**Comment by cx20** [comment]
@absconcept You must build `build/output/playcanvas.js` by yourself.

1. npm install
2. npm run build

Or rename `playcanvas-latest.js` to `playcanvas.js` and place the same folder.
https://code.playcanvas.com/playcanvas-latest.js

**Comment by absconcept** [comment]
Ok great, I will test first thing tomorrow, thank you

**Comment by mvaligursky** [comment]
this seems to be marked as [solved] on forum (I assume it's the same issue)
https://forum.playcanvas.com/t/solved-playcanvas-gltf-draco-compression-support/12973/5

so I'll close it here. Please (re)open an issue if you still have problems.
