### ISSUE TITLE
small mistakes in Typescript definitions

### ISSUE THREAD

**Issue by NokFrt** [playcanvas/engine#2280]
Hello,
Can you please fix the following issues? Thank you.

pc.createMesh()
- now all parameters are just number[], but some of them can be Float32Array or Uint32Array

SoundComponent.resume()
- parameter should be optional

SoundComponent.stop()
- parameter should be optional

**Comment by willeastcott** [comment]
Thanks for reporting this. I've made the corrections to the `pc.SoundComponent` API in #2281. However, I'm not comfortable casually changing the parameter types for `pc.createMesh` just yet. The function has been thoroughly tested with vanilla `Array` parameters. But I can't say for certain whether everything works fine with typed arrays without a lot of testing. Plus, various other related functions also take `Array` parameters, like `calculateTangents` and `calculateNormals`, and they would need to be updated too for consistency.

As it happens, `pc.createMesh` is on the verge of being deprecated anyway, since we now have an updated `pc.Mesh` API which allows you to do similar stuff.
