### ISSUE TITLE
Lightmap baking generates incorrect shader, causing WebGL errors in Safari.

### ISSUE THREAD

**Issue by Kulodo** [playcanvas/engine#2539]
Below is a minimal project and a screenshot showing the WebGL errors.
The errors are seen in Safari Mac/iOS.
Here is a forum thread https://forum.playcanvas.com/t/webgl-errors-safari-mac-ios-console/15699
This may be the code issue https://github.com/playcanvas/engine/blob/1db4031ab7d8cad5fb137ac456223c6af90e2c0d/src/scene/procedural.js#L915

https://playcanvas.com/project/734901/overview/blank-project-test

![c6e70c08ec0083a13954f103279d8990626a58bc_2_1310x1000](https://user-images.githubusercontent.com/74154551/98483156-fa04e780-21fd-11eb-93d0-770a5caf689b.png)

The only changes I made to the default blank project are:

Light
- checked bake light map
- unchecked Affect Dynamic

Box
- checked lightmapped

Plane
- checked lightmapped

**Comment by mvaligursky** [comment]
Quick investigation. In default mode lightmapping bakes directional lightmaps. During baking, a shader is generated, and it expects uv1 attribute, which is set here:
https://github.com/playcanvas/engine/blob/a7bbb5f10be66fd68890ab3081da6f1e339e617c/src/scene/lightmapper.js#L496

but forceUv1 does not seem to work reliably / correctly, and uv1 attribute declaration is not in the shader. See more about this issue here as well: https://github.com/playcanvas/engine/issues/1851
(workaround is not really applicable in this case).

see the generated shader in question:
[shader safari.txt](https://github.com/playcanvas/engine/files/5517599/shader.safari.txt)

The same shader is generated in Chrome, but that does not seem to generate any errors.

**Comment by mvaligursky** [comment]
possibly related https://github.com/playcanvas/engine/issues/2545

**Comment by raytranuk** [comment]
Is the problem that the default plane mesh is not modifiable and so even if flagged to have uv1 vertex attributes, they can't be added?

**Comment by mvaligursky** [comment]
It's not related to mesh, mesh has uv1, but out shader generation code has some bug and does not output uv1 coordinates from vertex shader even when options.forceUv1 is set to true.

**Comment by raytranuk** [comment]
ah - okay I will look into it
