### ISSUE TITLE
Separate Anim file into separate files for each class it contains

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2589]
This would make it easier to navigate and understand the code.

https://github.com/playcanvas/engine/blob/master/src/anim/anim.js

current content:

`export { AnimBinder, AnimClip, AnimCurve, AnimData, AnimEvaluator, AnimSnapshot, AnimTarget, AnimTrack, DefaultAnimBinder };`

**Comment by Dlewis89** [comment]
Hey @mvaligursky, I would like to take a crack at this as my first contribution to a open source project, if no one has started on it?

**Comment by mvaligursky** [comment]
@ellthompson works on this code base .. so let's see what he says - he might have some changes in flight in that code.

Welcome and thanks @Dlewis89 !

**Comment by Dlewis89** [comment]
No problem @mvaligursky. If you have anything else that you have for a junior dev. Let me know and I'll take a swing at it.

**Comment by mvaligursky** [comment]
What would you think about this?
https://github.com/playcanvas/engine/issues/2569

**Comment by Dlewis89** [comment]
Sure I'll take a look and let you know if I have any questions. Thanks @mvaligursky.

**Comment by ellthompson** [comment]
Hi @Dlewis89, noone I know of is actively working on the `src/anim/anim.js` file. If you'd like to take this on, that'd be great!

**Comment by Dlewis89** [comment]
Hey @ellthompson, sorry but I have to put this on hold for the meanwhile. I actually just got a job with php and laravel, so I have to buckle down and make sure learn the code base and hope my php is as good as I think since I was focusing on javascript but a job is a job lol. I really appreciate the opportunity and i'll come back to help out once I am settled in at the new job.

**Comment by ellthompson** [comment]
@Dlewis89 That's fine, i'll pick this task up myself. All the best with the new job!
