### ISSUE TITLE
Animation Component Trigger and Duration Problem (State)

### ISSUE THREAD

**Issue by devcem** [playcanvas/engine#2605]
New anim component has a problem with animation duration on "trigger" functionality.

If transition duration is not defined for state, when triggered animation finished, system doesn't switch to other defined animation properly. Transition only occurs if transition duration is defined.

I prepared a test project to see issue, in this example we have an animation called "**Idle**" and we have another animation called "Run". Run is not looped and expected behavior is when "**Run**" trigger finished, system should switch to idle.

You can reproduce this issue with pressing "**Space**" on project.

Project link : https://playcanvas.com/editor/scene/1052334
Project demo : https://launch.playcanvas.com/1052334?debug=true

1. Create 2 animations states, one of them should be called with trigger.
2. Make sure triggered animation has no transition duration value.
3. Trigger that function and see that it doesn't switch to original Idle animation after trigger complete.

If this intended, it's basically wrong, because some animations has no transition, transition make look animations bad for some cases. I would like to be able to set 0 for transition duration value.

**Comment by ellthompson** [comment]
Hi @devcem, I think you're right in that transitions with `0` or `null` durations should be treated the same as all other transitions. Bear in mind though that not looping the Run state will not ensure it plays for its duration before transitioning back to Idle. In order to keep the controller playing the Run state for its full duration, you'd need to set an exit time of `1.0` on the ANY > Idle transition.

I'll submit a PR to fix the `null` duration issue shortly.
