### ISSUE TITLE
Ammo JS is not included in dist

### ISSUE THREAD

**Issue by tones31** [playcanvas/engine#2609]
I thought it should be important to note somewhere that you must find and include ammo.js if using playcanvas offline. I was expecting it to be a part of the distribution file, `https://code.playcanvas.com/playcanvas-stable.min.js`.

**Comment by Maksims** [comment]
Ammo.js in an optional library to be included, and is not a part of the engine, although have close integration. Many projects do not use physics, so loading the library for those cases would be not desirable.

**Comment by willeastcott** [comment]
Yeah, ammo.js is considered by the engine to be an asset (of type 'module'). Same for Draco and the Basis transcoder. These modules can be found here:

https://github.com/playcanvas/engine/tree/dev/examples/src/lib

Since these modules tend to be loaded by the engine dynamically instead of being included into your app at build time (courtesy of say, Rollup or Webpack), they probably don't belong in the PlayCanvas Engine's NPM module distribution.

So I think I'll close this now since this was originally opened a year ago. But if anybody would like to follow up, be my guest. 😄
