### ISSUE TITLE
Mesh Morph “Set Weight” not working after changing scenes

### ISSUE THREAD

**Issue by dexterdeluxe88** [playcanvas/engine#2686]
When I use “setWeight” on a morph instance, it works like expected. But when I change the scene to another scene and back, the setWeight method doesn’t work anymore. I have created a small sample project: https://playcanvas.com/project/752588/

Found out that the issue doesn’t exist in v1.27 of the engine, but in v1.28

WORKS: http://launch.playcanvas.com/1065696?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.27.0.js

DOESN’T WORK: http://launch.playcanvas.com/1065696?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.28.0.js

Forum Post: https://forum.playcanvas.com/t/mesh-morph-set-weight-not-working-after-changing-scenes/16693

**Comment by mvaligursky** [comment]
I think this was already fixed, perhaps by https://github.com/playcanvas/engine/pull/2650

as this seems to work as expected?
http://launch.playcanvas.com/1065696?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-latest.js

Please reopen if that's not the case. We're hoping for engine release this week - needs a lot of testing due to large changes.

**Comment by dexterdeluxe88** [comment]
@mvaligursky yes, works as expected. thanks for having a look into the issue.
