### ISSUE TITLE
Allow using multiple copies of the same model with different material in Editor

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#290]
Currently you can't do it in editor, but can clone meshInstances in code.
I suggest generating new meshInstance, if user changes material or cast/receive shadow in editor, and if there's no another meshInstance in scene with identical parameters. If there is, replace current one with it.

**Comment by Maksims** [comment]
It is more of a question where to store and how to store such data.
Currently material mapping is store within model asset `data` property (json).
In order to enable overriding default materials, we need to extend model component with array that would contain same number of values as materials in model asset. And can have `null` or another material asset id, which means it overrides default material.

That way we will have still ability to inherit all material mappings from model asset and they can be changed in one place. And user can override them on model basis.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/dfe8d4b0d2ef380df45ed156fbcb88d81eb87ab1
