### ISSUE TITLE
Invalid Euler angles on zero scale

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2911]
The way Euler angles are calculated, produces an invalid result, if the scale is set to zero. Repro:

```js
entity.setLocalScale(0, 0, 0);
entity.setEulerAngles(10, 10, 10);
    
console.log(entity.getEulerAngles()); // Vec3 { x: NaN, y: NaN, z: 0 }
```

The use case:
We have some items spawn in the world in a little animation, which scales them from zero to normal size.

**Comment by kungfooman** [comment]
![image](https://user-images.githubusercontent.com/5236548/109012826-bb167700-76b2-11eb-9789-9a413172fe38.png)

**Comment by mvaligursky** [comment]
Well both rotation and scale share the 3x3 part of the Matrix4 .. and if you set scale to 0,0,0, whole 3x3 part is just zeros. So no angles are preserved.
We could do a more complicated solution perhaps that would try and keep rotation in a separate Quaternion or similar, but it's not likely worth the cost.

So the best we can do in the meantime I think is to return 0,0,0 instead of NaN, NaN, Nan.

Perhaps your animation needs to store and animate rotation / scale / translation independently if you need to handle scale of 0.

**Comment by LeXXik** [comment]
Right, so, currently I simply override the vector components to zero if one of them is of NaN value on the `getEulerAngles()` return. 

The problem came up when one wants to add some eulers to the current eulers. After an entity gets reset, that addition breaks the math. When the scale is zero, the rotation is of no importance, but when the scale becomes larger than zero on the next frame, then it should be possible to accumulate eulers. Giving an inital value of zero would allow it. I think returning zeros and documenting it in `getEulerAngles()` API docs would be a good resolution to this.

**Comment by Maksims** [comment]
NaN related issues with math, are sometimes an issue. Perhaps with DEBUG build, there could be a check.
I've caught myself many times, where after some math, I get NaN's. And due to amounts of code, the only way to find out what was a problem, is to insert dozens console.logs in between math ops. Just to nail down the source of an issue.

Perhaps a warning check in DEBUG build, which would check for NaN values could help to straight away find out that there is an issue after specific math operation due to provided inputs.
