### ISSUE TITLE
Post-effects applied on camera with render target issue

### ISSUE THREAD

**Issue by sinlyu** [playcanvas/engine#3090]
related to #2941 #3069 

forum post:
[here](https://forum.playcanvas.com/t/apply-bloom-only-to-specific-materials/18455/40?u=sinlyu)

description and explanation is given in the title and the forum post.

**Comment by mvaligursky** [comment]
- the problem seems to take place when the post processing is set up on camera using the Editor, but render target is set up later using the script.
- also some viewport scaling ratio issue seems to be there

**Comment by mvaligursky** [comment]
also it seems the sizing is based on backbuffer instead of render target, needs fixing.
https://github.com/playcanvas/engine/blob/master/src/framework/components/camera/post-effect-queue.js#L60
https://github.com/playcanvas/engine/blob/master/src/framework/components/camera/post-effect-queue.js#L272

**Comment by mvaligursky** [comment]
This should now be fixed, but as the repro no longer works due to API changes since it was created, I cannot confirm.
I'll close it. Please reopen if this does not work, with an up to date repro, sorry.
