### ISSUE TITLE
Class static - is not well supported on Safari

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#3199]
Since the move to ES6+, we've whitelisted many new JS language features, but as mentioned before: they should be well validated:
1. Do they compile well to ES5 by the current build system
2. Are they well supported in the market now, to keep the engine well supported by modern browsers, so engine users can use the ES6+ version directly.

Class `static` keyword has not been mentioned in [CONTRIBUTING.md](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md), and it is not well supported by Safari, [only in recent update 14.1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static#browser_compatibility) it has been added, which leaves a major part of Safari users on the older version.

**Comment by willeastcott** [comment]
Be careful about that page saying 14.1.

Here is an iPhone 6 running Safari 12.4.7:

![Image from iOS (30)](https://user-images.githubusercontent.com/697563/121100101-059aaa00-c7f1-11eb-9629-f5c2eea36675.png)

It's probably referring to static class *properties*, not static class functions.

If you look at the generated `playcanvas.mjs`, it preserves static class functions but Babel transforms static class properties to ES5.

So I don't really see the problem here, except that we don't explicitly say in the CONTRIBUTING.md that you can safely define static class functions and properties.

**Comment by willeastcott** [comment]
I have updated CONTRIBUTING.md to allow the use of the static keyword:

https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md#permitted-es6-features

Therefore, I am closing this issue. Please reopen if there's anything else relating to this that you'd like to discuss.
