### ISSUE TITLE
Drag and drop a new texture on a diffuse material don't update scene objects

### ISSUE THREAD

**Issue by alamboley** [playcanvas/engine#3294]
Hello,

I've several models in my scene sharing the same material.

When I select the material, in the assets, and drag (mouse down) a new texture on the diffuse image I preview the change. However when I drop (mouse up) the texture is changed but the game shows the previous rendering. I've to press the delete button and affect the texture to work as expected.

Same problem in fact using the selection/pen tool directly on the material for the texture :/

**Comment by yaustar** [comment]
Commit that caused the bug: https://github.com/playcanvas/engine/pull/3074

**Comment by yaustar** [comment]
Done some investigation:

Pre #3074:

```
                 material._assignTexture = function _assignTexture(parameterName, materialAsset, texture) {
			materialAsset.data[parameterName] = texture;
			materialAsset.resource[parameterName] = texture;
		};
```
When a texture was assigned to a material, `materialAsset.data[parameterName]` is set to the texture resource. This was 'bad' because `materialAsset.data[parameterName]` is also the assetId before _assignTexture was called.

However, when `_bindAndAssignAssets` is called, it was dependent on this by checking if `data[name]` was of type Texture. If it wasn't (which when we change textures in the Editor), it would assign the texture via `_assignTexture`
```
                     _proto._bindAndAssignAssets = function _bindAndAssignAssets(materialAsset, assets) {
			var data = this._parser.migrate(materialAsset.data);

			var material = materialAsset.resource;
			var pathMapping = data.mappingFormat === "path";
			var TEXTURES = standardMaterialTextureParameters;
			var i, name, assetReference;

			for (i = 0; i < TEXTURES.length; i++) {
				name = TEXTURES[i];
				assetReference = material._assetReferences[name];

				if (data[name] && !(data[name] instanceof Texture)) {
```

We now need to have some way of checking if the material has changed textures without reintroducing this behaviour.
