### ISSUE TITLE
Race Condition Vulnerability in PlayCanvas Stable JS file

### ISSUE THREAD

**Issue by s-y-help** [playcanvas/engine#3367]
After doing a code scan of the PlayCanvas Stable JS file, the race condition vulnerability is flagged out in line 33778.

Abstract: The call to get() in **playcanvas-stable.min.js** on line 33778 sets a callback that could lead to race condition.

Kindly advise how to rectify such vulnerability?

if (path.getExtension(url.original) === '.json') {
  		**http.get(url.load, {**
  			retry: this.maxRetries > 0,
  			maxRetries: this.maxRetries

**Comment by yaustar** [comment]
The `http` is the name of the variable. The way you could use it is:

```
http.get('https://google.com')
```

**Comment by yaustar** [comment]
Sorry, I'm getting confused with the email that was sent to support.

Yes, there can be a race condition where the data that was requested by http.get is not deterministic. As it's a request to the server, it's dependent on many conditions that aren't controlled by the engine. Eg. Size of file, network issues, server speeds etc.

It is possible to request:

Resource 1
Resource 2
Resource 3
Resource 4

And get back the order of 

Resource 3
Resource 4
Resource 2
Resource 1

It is the developers' responsibility to ensure that avoid situations where the order matters and only handle the response once everything is ready.

Eg The engine preloads assets and waits until they are all loaded from the server before starting the app.

**Comment by s-y-help** [comment]
Any suggestions on how we can avoid such scenarios?

**Comment by LeXXik** [comment]
So, the race condition may happen here, if the second response comes faster than the first one. The worst case scenario is that you would get an asset twice, since we are talking about the same resource request. You can do a check, and see if you already processed the resource you requested, and if so, ignore the response.

Another option is you can do it by saving an empty object, and compare it in the callback. If the object is different, it means there was already another request made, which changed it.
```js
const session = {};
this.lastSession = session;
http.get(..., () => {
    if (this.lastSession !== session) return;
});
```

**Comment by yaustar** [comment]
It depends on your app/code. For example, try to avoid scenarios where callback order matters and/or wait till all the requests have been done before continuing. 

It's similar to multithreaded programming where the developer has to ensure that work being done in each thread is independent from each other.

Once the work in each thread has been done, the code can then continue on the main thread.

The same principle applies here for HTTP requests.

A simple example can be found here: https://developer.playcanvas.com/en/tutorials/load-multiple-assets-at-runtime/

```
Preloader.prototype.loadAssets = function() {
    var self = this;
    
    // Find all the assets that have been tagged 'level'
    // In this example, they are in the 'assets-to-load' folder
    var assets = this.app.assets.findByTag('level');
    var assetsLoaded = 0;
    var assestTotal = assets.length;
        
    // Callback function when an asset is loaded
    var onAssetReady = function() {
        assetsLoaded += 1;        
        
        // Once we have loaded all the assets
        if (assetsLoaded === assestTotal) {
            self.onAssetsLoaded();
        }        
    };
    
    // Start loading all the assets
    for(var i = 0; i < assets.length; i++) {
        if (assets[i].resource) {
            onAssetReady();
        } else {
            assets[i].ready(onAssetReady);
            this.app.assets.load(assets[i]);
        }
    }
    
    if (!assets.length) {
        this.onAssetsLoaded();
    }    
};
```
(Note: The asset loader uses the http class under the hood). 

Here you can see that we request all the assets at once:
```
    // Start loading all the assets
    for(var i = 0; i < assets.length; i++) {
        if (assets[i].resource) {
            onAssetReady();
        } else {
            assets[i].ready(onAssetReady);
            this.app.assets.load(assets[i]);
        }
    }
```
And they can be loaded in any order due to the nature of HTTP network requests.

But the code waits till they all load before continuing with logic to show the models on the screen.
```
    // Callback function when an asset is loaded
    var onAssetReady = function() {
        assetsLoaded += 1;        
        
        // Once we have loaded all the assets
        if (assetsLoaded === assestTotal) {
            self.onAssetsLoaded();
        }        
    };
```

**Comment by yaustar** [comment]
@s-y-help Have you actually hit an issue where you have race condition in a project? If so, we can help more on the forums on how to avoid it.

**Comment by willeastcott** [comment]
It's been five months since @yaustar requested more info from @s-y-help. As a result, I'm going to assume that there is no longer a problem and close this issue. However, if you believe this to be premature, let me know and we can reopen it.
