### ISSUE TITLE
Text Element in 3D space with outline has rendering artifacts at a distance

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3477]
Forum: https://forum.playcanvas.com/t/transparency-bug-on-text/21863
Project: https://playcanvas.com/project/830335/overview/3d-ui-text-outline-bug

Text Element must have outlines for this issue to occur:
Related: https://github.com/playcanvas/engine/issues/3087

![image](https://user-images.githubusercontent.com/16639049/133063454-dc4704af-c596-478e-9c7f-610ad9612856.png)

**Comment by sakidev** [comment]
This also happens when the render resolution is pretty low, example with one of my games:

706x444:
![image](https://user-images.githubusercontent.com/49696473/133990653-7aa8e5b5-e4f9-409c-8459-6bcf82d130b1.png)

1239x801:
![image](https://user-images.githubusercontent.com/49696473/133990671-d8ef8c28-6e28-4247-8ec8-2fd109f29b30.png)
