### ISSUE TITLE
Unable to use calculateTangents property

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#3479]
When using a procedural.js, passing `{ calculateTangents: true }` to constructor throws an error `calculateTangents is not a function`.
```js
const mesh = pc.createTorus(device, {
    calculateTangents: true
});
```

![image](https://user-images.githubusercontent.com/5677782/133137434-05655e6b-50fb-4bdd-ba92-9c392244b660.png)

**Comment by mvaligursky** [comment]
see example here on how this needs to be used:
https://developer.playcanvas.com/en/api/pc.html#calculateTangents

**Comment by willeastcott** [comment]
@LeXXik is right - there is a bug here, @mvaligursky. Check this line:

https://github.com/playcanvas/engine/blob/master/src/scene/procedural.js#L313

And then this line:

https://github.com/playcanvas/engine/blob/master/src/scene/procedural.js#L360

This bug has probably been around since we removed the `pc` namespace from the engine source. So the line about used to call `pc.calculateTangents`. But the name clash with the local var was not spotted.

**Comment by mvaligursky** [comment]
I missed that, thanks @willeastcott . 
Fixed now, thanks @LeXXik !
