### ISSUE TITLE
Custom attributes on material's shader definitions.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#3485]
When constructing a `Mesh` it is possible to add custom attributes using `setVertexStream` and `SEMANTIC_ATTR*` constant.
But when the shader is created for StandardMaterial, unfortunately it is not adding relevant varying semantic to `definition.attributes` object, so no attributes will be passed.

The workaround is to patch `standard` generator `createShaderDefinition`, and force add a relevant attribute to the definition, but it is required to check if vertex shader code contains a particular substring in order to identify the right shader for the custom attribute.

It would be great to have a generic way for Material to define relevant semantic to attribute mapping functionality.
Something like:

```js
material.defineAttribute('vertex_custom_attribute', pc.SEMANTIC_ATTR15);
```

So shader for it would include relevant attributes in definitions.

**Comment by mvaligursky** [comment]
It should likely also allow to set semantic used by the instancing, which is currently hardcoded. See the change here which modified it .. this should be settable by the user instead of hardcoded in the engine https://github.com/playcanvas/engine/commit/dc126317ea0d67d9542a00c9bb44481c3a64fd10#diff-9ca32de26f8325e11d4a0936116c4a9a8c8bbcce24630887f90f72070dfb64fc

**Comment by LeXXik** [comment]
Bumping up. Would be great to have.
