### ISSUE TITLE
Max texture image units limit reached with 1.47.0

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#3561]
Hi, we are getting the following error on some of our custom materials (they use custom shaders) with 1.47.0:

![Screenshot 2021-10-12 104600](https://user-images.githubusercontent.com/29543178/136923431-6153190d-87eb-4905-a6e0-04247a20a584.jpg)

I imagine there were changes to the shader system and new texture samplers where introduced by default. Could you help us track down the samplers that were added so we can rework our shaders to avoid reaching this limit?

Using engine v1.46.5 the error goes away and shaders compile as expected.

**Comment by mvaligursky** [comment]
Are you using clustered lighting? Any improvement when you disable it?
Any repro we could look at?

I guess the best way to track this down would be to log out all the shaders that are getting compiled to see what we go over the limit.

**Comment by mvaligursky** [comment]
A repro would not help I guess .. we probably understand what is going on. Clustered lighting uses these fixed amount of samplers (5):
- clusters texture (the cells in the world space)
- lights float texture (for HDR data)
- lights 8bit texture (for LDR data)
- shadow atlas
- cookie atlas

You use directional shadow map .. so that's another sampler.

And you're left with 10 for other things. Does your terrain use more than 10 samplers?

**Comment by leonidaspir** [comment]
That would help tons, to have those switches in place.

In any case we definitely plan to revisit those shaders of ours and see if we can optimize our side. Very curious how fireflies shadows cast on our grass 😇

**Comment by mvaligursky** [comment]
I'll get it done in next few days.
Haha your fireflies have some serious lights on them if they can cast shadows ;) But curious to see it as well :) Maybe still to spot lights pointing down instead of omnies?
