### ISSUE TITLE
Very long build times (1min+), need speedups

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#3575]
Currently, the engine takes a very long to build.
`npm run build`, on a good laptop (4 years old top gaming laptop), takes 1 minute and 16 seconds. And about 20 seconds for `playcanvas.js` file build.
Would be great if there would be a developer-focused build target (with watch variant), that would be built within few seconds (as fast as possible), that does not need many validations, etc, but needs for a quick test during the development process.

Previously builds were way faster than now.

**Comment by belohlavek** [comment]
What's the bottleneck? Have you considered esbuild?

**Comment by mvaligursky** [comment]
see a relevant ticket here https://github.com/playcanvas/engine/issues/2103

**Comment by willeastcott** [comment]
@belohlavek The bottleneck (or main contributor to the build time) is Babel. If you disable Babel in the `rollup.config.js`, build time drops by about 65%.

**Comment by Maksims** [comment]
> @belohlavek The bottleneck (or main contributor to the build time) is Babel. If you disable Babel in the `rollup.config.js`, build time drops by about 65%.

Probably worth investigating for a very fast build option, for development purposes, with a watcher, that allows the developer to iterate quickly on the engine.

**Comment by willeastcott** [comment]
This PR allows you to load the engine from source without having to build it:

https://github.com/playcanvas/engine/pull/3850

Maybe not useful for Editor users at the moment, but maybe interesting for engine-only devs or anybody running the engine in Node.

**Comment by willeastcott** [comment]
I have researched ways to get Babel to execute faster and it doesn't seem there is anything further we can do at this time. So since this isn't really a PlayCanvas issue, I'm going to close this. However, I'm still very interested in anyone's ideas to improve this. So if you think I've missed some practical thing we can be doing to achieve better build times, let me know and I can re-open the issue.

**Comment by yaustar** [comment]
Could we have a no babel build option for dev purposes? (Eg running against the Editor)

**Comment by willeastcott** [comment]
Yes, we could do that. But I just tried `npm run watch:es5` and it takes 2.9 seconds to rebuild `playcanvas.js` instead of 13.8s for `npm run build:es5`.

![image](https://user-images.githubusercontent.com/697563/147991859-dda297b7-eb42-4483-9098-845b922e4d68.png)

As a result, I think we can just leave this closed.
