### ISSUE TITLE
Should disabled entities load assets?

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#364]
Currently a scene is loaded all assets referenced by components are loaded (if they are not already preloaded). This is independent of whether the entity is enabled or not.

Should we delay this load until the entity is enabled?

**Comment by Maksims** [comment]
I think for many cases allowing a developer to decide - is best case here. Default behaviour should be least magical and most simple, providing functionality to start loading if required.
So +1 for "don't load unless asset has to be rendered".

**Comment by vkalpias** [comment]
I guess I would also go for loading it when enabled. I can imagine a case though where a user chose to not preload an asset so that the game starts quickly but then when inside the game start streaming the asset even if the component that uses it is disabled. So maybe it should be a choice. Or I guess the default could be the first and if the user wants the latter, then he can do it by hand in code.

**Comment by Maksims** [comment]
@vkalpias you mean it should be not loaded if entity is disabled, and if user want to load still, can do it through code?

**Comment by vkalpias** [comment]
Yeah

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/89aaa6f65795269cf90c26bc4e64cda1282eca9f
