### ISSUE TITLE
Failing to draw to render target in 1.51.5

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#3899]
The application throws, if I select 1.51.5 in Editor. Works fine if 1.50.2 is selected.

The error:
![image](https://user-images.githubusercontent.com/5677782/149631975-87f7e9fe-b93d-4632-9949-fab0d99b15f0.png)
![image](https://user-images.githubusercontent.com/5677782/149632062-9090ed6b-194f-4f4d-ae75-5a3026f02a9f.png)

The following line causes it:
```js
pc.drawQuadWithShader(device, target, shader);
```

Also, the error is thrown if a graphicsDevice of a new PC instance is used. I create a new app for calculating stuff on GPU this way:
```js
// pseudo
const width = 2;
const height = 2;
const offscreen = document.createElement('canvas');
offscreen.width = width;
offscreen.height = height;
const app = new pc.Application(offscreen);
app.start();
app.setCanvasFillMode(pc.FILLMODE_NONE, width, height);
app.setCanvasResolution(pc.RESOLUTION_FIXED, width, height);
app.autoRender = false;
```

If a `graphicsDevice` is used from the current instance, then there is no error:
```js
const app = pc.Application.getApplication();
```

**Comment by mvaligursky** [comment]
Would you have some simple repro application for this? That would make it easier to track down.

**Comment by LeXXik** [comment]
@mvaligursky I extracted the relevant code here:

https://playcanvas.com/editor/project/870544

**Comment by mvaligursky** [comment]
I think the problem is that you're calling update on the application 2 from inside the update of the application1 .. and the Application.getApplication() function does not handle that and keeps returning the original application.

You could maybe update the variable that function returns / restore it afterwords. But I wonder what's the reason to create a new application / device instead just using original app/device and rendering to texture?

**Comment by LeXXik** [comment]
I can't recall why I added an option of an offscreen canvas, to be honest. It is actually off by default (the existing app is used instead), I don't use it. I just noticed an error during the code refactor and decided it was worth making an issue. I would assume any PC version should crash if what you are saying is true, but I do not see the error in the prior version. Feel free to close the issue if you consider it is by design.

**Comment by mvaligursky** [comment]
Yep thanks, I'm keeping it open to add few assets to the code that should trigger if we try to render mesh / shader or similar on a device that was created on a different device. If I confirm that is the case, I'll leave the asserts in the warn user, as that is by design. `Application.getApplication()` is not ideal, and that's a source of the problem though, but I'll confirm that.
