### ISSUE TITLE
Entity.destroy warning

### ISSUE THREAD

**Issue by weilichuang** [playcanvas/engine#3945]
>...
>const a = new pc.Entity('a',app);
>const b = new pc.Entity('b',app);
>a.addChild(b);
>a.destroy();

will warn : GraphNode#removeChild: 'b' is not a child of 'a'

**Comment by willeastcott** [comment]
This is because I just added a warning message here:

https://github.com/playcanvas/engine/blob/dev/src/scene/graph-node.js#L1300

But `Entity#destroy` seems to be doing some manipulation of its own of the `_children` array:

https://github.com/playcanvas/engine/blob/dev/src/framework/entity.js#L495-L539

From looking at `destroy`, it feels like it could benefit from a refactor. However, for now, I could just remove the warning message.
