### ISSUE TITLE
1.52.2 breaks screenshot tutorial

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4087]
Project: https://playcanvas.com/project/438437/overview/capturing-a-screenshot

Version 1.52.2 just gives a transparent screenshot: https://launch.playcanvas.com/476102?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.52.2.js

![screenshot (18)](https://user-images.githubusercontent.com/16639049/156820479-bbebcabe-4b54-4f33-9391-6e4817c32dd4.png)

Version 1.52.1 works fine https://launch.playcanvas.com/476102?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.52.1.js

![screenshot (20)](https://user-images.githubusercontent.com/16639049/156820675-1d22f9f4-4f00-414a-b7d7-150baa99d83d.png)

**Comment by mvaligursky** [comment]
This is the PR that broke this: https://github.com/playcanvas/engine/pull/4014

The reason is that the script uses private Texture._glTexture which has been moved to a different class now.

`._glTexture` needs to change to 
`.impl._glTexture`

I'm adding a deprecated message to the engine, even though this is a private interface.

**Comment by yaustar** [comment]
Had a talk with the team in the meeting today and we will deprecate access to '_glTexture' with a warning but will still return the previous result until we create proper access API or screenshot functionality
