### ISSUE TITLE
GLB vertex colors not appearing 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4118]
Forum: https://forum.playcanvas.com/t/draco-glb-diffuse-emissivevertexcolor/24769

Test project with Draco and uncompressed GLBs: https://playcanvas.com/editor/scene/1363413

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/16639049/158355893-89fe7608-3837-4668-a0d3-6b6476a94061.png">

Should look like this:
![image](https://user-images.githubusercontent.com/16639049/158356052-329d21c1-a387-48ba-bf5a-6cc72d64efda.png)

**Comment by willeastcott** [comment]
The problem here seems to be that the GLB contains no materials. The engine just uses a 'default material' if no materials are found:

https://github.com/playcanvas/engine/blob/main/src/resources/parser/glb-container-resource.js#L81

Materials created by the `GlbParser` enable tint+vertex colors:

https://github.com/playcanvas/engine/blob/main/src/resources/parser/glb-parser.js#L1007-L1008

But the default material does not have this enabled. The `GlbContainerResource` constructor should probably be passed a default *glTF* material, rather than just a vanilla `StandardMaterial`.

**Comment by willeastcott** [comment]
So there are actually two problems here. One affects the uncompressed model and one affects the Draco compressed model.

* **Uncompressed**
  * Problem: A 'default' `StandardMaterial` is applied to mesh instances when the GLB does not explicitly specify a material.
  * Solution: Set the `GlbParser`'s default material to be a default **glTF** material (as created by `createMaterial` in glb-parser.js.
* **Draco Compressed**
  * Problem: The Draco module function `normalized()` returns false for the color vertex attribute. It should return true.
  * Solution: I'm less sure what to do here. But I tried setting `normalized` to true for all Uin8 attributes and that fixed the problem.

**Comment by willeastcott** [comment]
It's probably best if I hand this over to @mvaligursky now since I'm not 100% whether my solutions fully resolve the problems.

**Comment by mvaligursky** [comment]
Great investigation @willeastcott !
