### ISSUE TITLE
Function callbacks don't generate API pages

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4242]
We have a number of function callback types that used to generate API pages/docs but no longer do.

Examples:
LoadAssetCallback
LoadSceneDataCallback
LoadHierarchyCallback
LoadSettingsCallback
AssetReadyCallback

**Comment by willeastcott** [comment]
Aren't these them:

https://developer.playcanvas.com/api/pc.html#LoadAssetCallback
https://developer.playcanvas.com/api/pc.html#LoadSceneDataCallback
https://developer.playcanvas.com/api/pc.html#LoadHierarchyCallback
https://developer.playcanvas.com/api/pc.html#LoadSettingsCallback
https://developer.playcanvas.com/api/pc.html#AssetReadyCallback

**Comment by willeastcott** [comment]
So the problem is that _references_ to these callback have an URL of the form:

https://developer.playcanvas.com/api/pc.AssetReadyCallback.html

But the actual URL is:

https://developer.playcanvas.com/api/pc.html#LoadAssetCallback

We'll probably need to edit the JSDoc template for the API reference to handle these URLs properly.

**Comment by willeastcott** [comment]
Fixed here: https://github.com/playcanvas/playcanvas-jsdoc-template/pull/41
