### ISSUE TITLE
Normal map does not work for particle systems

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#447]
Try using a mesh with a texture and a normal map - the normal map does not seem to make a difference.

**Comment by guycalledfrank** [comment]
Mesh particles are currently very limited by design. They don't have UVs, normals and tangents.
Also, simply enabling normal map would be likely not enough, because then people will want to emit shiny things, so basically we need to connect particles and materials we use for normal objects.
I created another issue for it: https://github.com/playcanvas/engine/issues/452
