### ISSUE TITLE
Crash when using non-preloaded material

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4498]
When a render component is changing to a material that was not preloaded, the application crashes.

Repro: https://playcanvas.com/project/965390/overview/material-issue

1. Click a mouse to change the cube material.
2. App will crash.

Repro in 1.54.1 and 1.53.4.

There is no crash, if the changed material is set to preload.

**Comment by kungfooman** [comment]
So when you `const red = this.red.resource;` and the asset is not loaded, you receive `undefined` and then you set `undefined` to type `Material`?

I don't think that is right in the first place and a clear type error, what should happen otherwise? Maybe preallocate a `StandardMaterial` and assign it to `Asset#resource`, that is then "updated" later by `Asset`, once its loaded?

**Comment by slimbuck** [comment]
Yep, you'd have to get the red material asset and 'load' it as usual. Once that's complete, asset.resource should be valid and you can set it on the render component.

Perhaps we can also issue a debug message when render.material isn't set cc @mvaligursky ?

**Comment by LeXXik** [comment]
Yes, I understand the reasoning and the cause. Currently the crash is cryptic and hard to debug, especially in multi-user projects.

**Comment by yaustar** [comment]
Yeah, the error message is pretty far from the code that's causing it from the user point of view:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/16639049/182604838-e1506348-9cb7-4d0d-9dfb-110f70f2f886.png">

**Comment by mvaligursky** [comment]
Debug warning added in #4524.
Closing this ticket, as there is no other issue.
