### ISSUE TITLE
Element mouse click event does not fire if the user has touch clicked on it first

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4832]
Project: https://playcanvas.com/project/1006310/overview

Repro steps:

1. Launch the tab in phone emulator mode
2. Touch click on the element a few times. It will change color on each click
3. Come out of phone emulator
4. Mouse click on the element a few times. The click event is not fired

This can cause issues on devices like laptops where you have both touch and mouse controls and are likely to swap between the two.

https://user-images.githubusercontent.com/16639049/200815692-9515b56d-f800-4d89-901b-b7f65cf18d46.mp4

**Comment by yaustar** [comment]
This is because the clickedEntities are not cleared until the next touch up event that the mouse up event is checking against.

https://github.com/playcanvas/engine/blob/main/src/framework/input/element-input.js#L742

Wondering it be okay to do a setTimeout to clear them on the next frame?

**Comment by kungfooman** [comment]
Project link is 404

**Comment by yaustar** [comment]
Oops. Fixed @kungfooman

**Comment by kungfooman** [comment]
> Wondering it be okay to do a setTimeout to clear them on the next frame?

I like your idea, I just don't know the specific "next frame" time, so I made a few tests:

iPhone/Safari is not emulating mouse events after touch in the first place (should that be special cased?).

iPhone/Chrome delay between touchend and mouseup is 47ms:

![iphone-chrome](https://user-images.githubusercontent.com/5236548/201340269-a45acdb5-138a-4737-a927-d72e989c34be.jpg)

Android/Chrome delay between touchend and mouseup is 269ms on my device:

![android-chrome](https://user-images.githubusercontent.com/5236548/201340352-37fe736c-a22b-4053-a37a-b33d0d933184.jpg)

I think we should just delete the guid in clickedEntities after mouseup so far while saving `Date.now()` instead of a boolean, so we can just make a "mouse after touch timeout check" of lets say 300ms to ignore the mouse click event.
