### ISSUE TITLE
activeStateProgress does not return 1 at the end when speed is greater than 1

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4903]
Forum: https://forum.playcanvas.com/t/activestateprogress-does-not-return-1-at-the-end-when-speed-is-greater-than-1/28663

> Hi all,
> I’ve noticed that AnimComponent’s activeStateProgress does not return 1 at the end when the speed is greater than 1.
> 
> I have an animation with a duration of 4.5 secs when the animation speed is 1 and I run activeStateProgress regularly and at the end, I get the result 1. But when I update the animation’s speed to for example 3, I get 0.26 at the end.
> 
> Is this a bug?

Example project: https://playcanvas.com/project/951561

> When you keep pressing key P, at the end of the animation you will see that activeStateProgress value is 0.5 , instead of 1.

**Comment by ertugrulcetin** [comment]
Also I have a suggestion that might work for `_getActiveStateProgressForTime`;

```
const activeClip = this._animEvaluator.findClip(this.activeStateAnimations[0].name);
if (activeClip) {
    const speed = this.activeStateAnimations[0].speed;
    return (time * speed) / activeClip.track.duration;
}
```

**Comment by ertugrulcetin** [comment]
Hi @ellthompson, any updates on this one?

**Comment by ellthompson** [comment]
Hi @ertugrulcetin 

It looks like your solution is the right way forward for this issue. This also affects the exit time of state transitions. Currently if the source state of a transition has a modified speed value, the exit time check doesn't respect that speed value. It'd be great if you'd like to submit a PR for address this, otherwise I can.

Perhaps this logic should also be moved to the AnimClip class in a function like:
```javascript
    progressForTime(time) {
        return (time * this._speed) / this._track.duration;
    }
```
Which can then be called by the AnimController's `_getActiveStateProgressForTime ` function on the `activeClip` if available.

**Comment by ertugrulcetin** [comment]
> This also affects the exit time of state transitions.

Yes, I also noticed that one as well, was going to let you know after this one. Let me check what I can do, it I get stuck then I'll let you know that you can create the PR yourself.

**Comment by ertugrulcetin** [comment]
Here: https://github.com/playcanvas/engine/pull/4913
