### ISSUE TITLE
Area Light rendering artifacts on materials

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5116]
Project https://playcanvas.com/project/1044972/overview/f-playcanvasomnilight

Clear coat and very high Glossiness materials have black outlines with area lights
<img width="620" alt="image" src="https://user-images.githubusercontent.com/16639049/222101558-6b5b24e2-d22d-4b49-b560-7aa32412654f.png">

The disc light has a 'fuzziness' black area when an object is close to it
<img width="219" alt="image" src="https://user-images.githubusercontent.com/16639049/222101728-b0e49290-1b04-4b73-9830-5354be752db8.png">

Reported to only happen on Mac and iOS.

**Comment by mvaligursky** [comment]
Another mention of this: https://forum.playcanvas.com/t/issue-with-area-light-area-lights-creating-a-black-spot-and-black-line/35153

cloned repro project: https://playcanvas.com/project/1197986/overview/area-light-issue-fork

**Comment by slimbuck** [comment]
Potentially related:

I noticed this code using `vNormalW`, which is wrong. https://github.com/playcanvas/engine/blob/main/src/scene/shader-lib/chunks/lit/frag/ltc.js#L106

It should either have `worldNormal` passed in or it should use `litArgs_worldNormal` directly.

(vNormalW is the pre-normalised vertex attribute which doesn't include normalmap perturbation etc and isn't normalised).

**Comment by mvaligursky** [comment]
This is fixed by https://github.com/playcanvas/engine/pull/7015

before:
<img width="859" alt="Screenshot 2024-10-09 at 11 40 40" src="https://github.com/user-attachments/assets/ac877a39-88fa-4c8e-a3a7-e753b6a04fc0">
now
<img width="681" alt="Screenshot 2024-10-09 at 11 40 46" src="https://github.com/user-attachments/assets/a1cef0eb-af90-4c40-8bff-ddb4da350735">
