### ISSUE TITLE
MeshInstance.castShadow not updating shadows

### ISSUE THREAD

**Issue by animech-sijo** [playcanvas/engine#5117]
Came accross this bug described in this thread: https://forum.playcanvas.com/t/meshinstance-castshadow-not-working-properly/6887/

If we're disabling shadow casting on MeshInstances:
```
var meshInstances = this.entity.model.meshInstances;
for (var mi = 0; mi < meshInstances.length; mi++) {
     meshInstances[mi].castShadow = false;
}
```
The shadow does not disappear unless we disable and enable the entity:
```
this.entity.model.enabled = false;
this.entity.model.enabled = true;
```

The expected behavior is that shadows update as soon as MeshInstance.castShadow is updated.

**Comment by mvaligursky** [comment]
MeshInstance. castShadow is a private flag, not part of public API, so there is no expected behaviour when changing this.
The public API is RenderComponent.castShadows, which I believe behaves correctly.

But in saying that, I think it could be useful to make it to work, similarly to how MeshInstance.visible works, which does not involve the cost of updating the LayerCompositions, but simply skips the mesh during the frustum culling when rendering to shadows.
