### ISSUE TITLE
Implement dither transparency as one solution for order independent transparency

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5159]
Not a general solution, but cheap and useful.
https://danielilett.com/2020-04-19-tut5-5-urp-dither-transparency/

![image](https://user-images.githubusercontent.com/59932779/225690784-0cf3ea3b-b62e-496e-ac88-3cb2f0fbac47.png)

**Comment by querielo** [comment]
I'm not sure that it has to be a part of the engine since it can be done without it. Also, it is not clear what kind of pattern should be used: Bayer, white noise, blue noise and so on. 

### Example.

**Source code**: https://github.com/querielo/playcanvas-dither-transparency

**Project**: https://playcanvas.com/project/1051789/overview/dither-transparency

**Comment by LeXXik** [comment]
Is the project private?

**Comment by querielo** [comment]
Ouch. I forgot about it :-)

Fixed.

https://playcanv.as/p/qdYtm4jw/
https://playcanvas.com/project/1051789/overview/dither-transparency

**Comment by yaustar** [comment]
> I'm not sure that it has to be a part of the engine since it can be done without it. 

IIRC, the goal was to have a script that was officially supported by PlayCanvas rather than adding it to the engine directly. So it would live here: https://github.com/playcanvas/engine/tree/main/scripts

**Comment by mvaligursky** [comment]
Script vs in engine is not something that was decided yet, it can go either way.
