### ISSUE TITLE
Create modern looking bloom post-effect

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5187]
Currently, the engine only has a simple bloom effect, and a modern implementation is needed.

references:
https://learnopengl.com/Guest-Articles/2022/Phys.-Based-Bloom
https://www.froyok.fr/blog/2021-09-ue4-custom-lens-flare/
https://twitter.com/iced_coffee_dev/status/1617580408576565251?t=OYAlQMbMAx4PYCKlx7HplQ&s=03

**Comment by SashaRX** [comment]
I experimented with it on this tutorial   https://playcanv.as/b/491d8a85

**Comment by SashaRX** [comment]
> That looks cool, @SashaRX. Did you experience any problems or limitations using the technique from that article?

In general, everything went really fast, despite my poor programming skills). I still haven't worked out how to use blendState and pc.drawQuadWithShader. Here it uses render to hdr render target, I use linear space, it's possible that this is not correct everywhere, since I didn't specify that albedo should be srgb for example, but it seems to be correct.

**Comment by MAG-AdrianMeredith** [comment]
Looks good I'll be interested to see how that compares to our version.  I made a custom enhancement to playcanvas hdr mode so that it renders to 11bits not 16bit.  This was a lot faster to render on my m1 macbook (3-4ms).  The one issue still remaining is alpha blended objects look different like they are being double tonemapped or something....

**Comment by mvaligursky** [comment]
I'm definitely keen to have this working on 11bits as well, to have a wider device support as well.
Both results look fantastic.

**Comment by GSterbrant** [comment]
I am also adding this link to the UE current bloom method for visibility: https://www.froyok.fr/blog/2021-12-ue4-custom-bloom/

**Comment by mvaligursky** [comment]
Another awesome work on this:
https://forum.playcanvas.com/t/physically-based-hdr-bloom/31759

**Comment by mvaligursky** [comment]
@GSterbrant - you did some work on this as well, could you please create a PR for this (just attach the file in current state), link the PR here and close the PR (for now), just to keep reference to that file.

**Comment by mvaligursky** [comment]
https://twitter.com/turanszkij/status/1680836739399667713

**Comment by MAG-AdrianMeredith** [comment]
I like that custom ue4 one.  I believe I can share the source to my implementation if you're interested though its still not 100% imo

**Comment by mvaligursky** [comment]
Ideally we'd implement in using this system when ready: https://github.com/playcanvas/engine/issues/5687
