### ISSUE TITLE
Normal blending causes transparent color buffer

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#5340]
### Description

It looks like the normal blending is defined "unorthodoxly": https://github.com/playcanvas/engine/blob/6d4766e7dd7cdc2e4ecfac439e4cb4b85b2e0404/src/scene/materials/material.js#L27

https://github.com/playcanvas/engine/blob/6d4766e7dd7cdc2e4ecfac439e4cb4b85b2e0404/src/scene/materials/material.js#L294

So,
```
resAlpha = (1 - srcAlpha) * dstAlpha + srcAlpha * srcAlpha < 1, if srcAlpha < 1
```
instead of
 ```
 resAlpha = (1 - srcAlpha) * dstAlpha + 1 * srcAlpha
 ```
 or something like this.

As you can see here if we render transparent glass over opaque object the canvas becomes transparent too. It can cause issues with post-processing or materials that use Color Grab.

<img width="513" alt="Screenshot 2023-05-19 at 19 48 54" src="https://github.com/playcanvas/engine/assets/104348270/4d3d4a4b-1a1b-481c-94ea-be8cf873c8e6">

Can we change it to 
`gl.blendFuncSeparate(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ZERO);` or `gl.blendFuncSeparate(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA);`?

**Comment by MAG-AdrianMeredith** [comment]
I concur, this wreaked havok with our AR app as any translucent material caused you to see the real world through it so we manually set the blend mode

**Comment by GSterbrant** [comment]
Hello!

I understand what we're looking for here, which is basically the default values when calling glBlendFuncSeparate and only modifying the color functions. However, our API is congruent with OpenGL, as in, if you use glBlendFunc (not separate), the color and the alpha use the same function. https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml

**Comment by mvaligursky** [comment]
This is likely related to this as well: https://github.com/playcanvas/engine/issues/1923

**Comment by mvaligursky** [comment]
To me it seems we should expand the definitions of those standard material blend modes, such as https://github.com/playcanvas/engine/blob/6d4766e7dd7cdc2e4ecfac439e4cb4b85b2e0404/src/scene/materials/material.js#L27 to include separate blend values for alpha channel blending, that is more useful, instead of defaulting them to the color blending values.

But that would change the long standing behaviour and could break projects where people depend on existing modes.
We could perhaps just add few additional modes, but I'm not sure what would be the most useful here for multiple cases.
