### ISSUE TITLE
Reallocation of rect by `getBoundingClientRect`

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#537]
Calling getBoundingClientRect every frame re-allocates a ClientRect object. This contributes to GC stalls,

https://github.com/playcanvas/engine/blob/master/src/graphics/device.js#L540

**Comment by Maksims** [comment]
There is no alternative to "update" the rect without re-allocating a new one.
In order to implement reliable updates of canvas resolution, engine either user shall implement functionality to call DOM related methods to get size and position of canvas. In all cases querying DOM for such properties will lead to reflows.
Using getBoundingClientRect makes one reflow instead of many by individually calling clientWidth, clientHeight, etc.

I don't see alternatives to this with easy work we do for users already by managing resolution of canvas.
