### ISSUE TITLE
Shader compilation speed regression in Chrome 115

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5526]
We're seeing a pretty significant drop in shader compilation speed in Chrome / Edge 115 on Windows, compared to 114. We have a test example that compiles 18 large shaders (https://playcanvas.github.io/#/graphics/shader-compile). This used to take 2.5s to compile those in 114, vs 20s in 115. Those shaders are pretty complex and use clustered lighting. If the clustered lighting is disabled, the regression is 1.4s -> 3.3s. Would anybody have any idea about what has changed? It's the same story on Canary 117. The profiler as expected shows spending about 1s per shader in getProgramParameter, which is the blocking operation waiting for the results of the compilation and linking. Note that all shaders start the compilation, then all shaders start linking, and only then they start waiting for the results, which should / used to give us their parallel compilation. Is this no longer working?

Screenshot from profiling on 115, not that each shader compilation taking almost 1s.

![Screenshot 2023-07-31 at 16 02 49](https://github.com/playcanvas/engine/assets/59932779/f4d52fbe-daf2-4fa7-a746-0da6148e9e31)

forum thread: https://forum.playcanvas.com/t/performance-issues-in-chrome-115/32417/10

**Comment by mvaligursky** [comment]
logged a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1468993

**Comment by mvaligursky** [comment]
suggestion from WebGL Matrix room:

<img width="987" alt="Screenshot 2023-07-31 at 17 58 34" src="https://github.com/playcanvas/engine/assets/59932779/30ce4b67-9e7a-4052-a868-beecc82e1a81">

**Comment by mvaligursky** [comment]
@Maksims - can you please confirm this is Chrome 115 issue as well.

**Comment by mvaligursky** [comment]
Yes, 115+ is slow, 114 is fine, cheers.

**Comment by kungfooman** [comment]
Link without loading everything else: https://playcanvas.github.io/iframe/?category=Graphics&example=ShaderCompile

I'm on: Version 115.0.5790.110 (Offizieller Build) (64-Bit)

But Linux, not Windows.

Performance trace:

![image](https://github.com/playcanvas/engine/assets/5236548/14136047-1785-4776-8aed-859c36c29209)

It all doesn't take longer than ~3 seconds.

I fooled around with libangle for a C++ project in the past and it's quite complicated... https://github.com/google/angle#level-of-opengl-es-support-via-backing-renderers

They support many backends (that's why I picked it, to test "WebGL" in a DirectX application) and I guess that's what leaves it to the mercy of DirectX on Windows. Since I don't see an issue on Linux, maybe they linked it against another DirectX version / setting / backend?

I just googled and in 2021 it seemed to be possible to pick another backend via `chrome://flags/` https://support.google.com/chrome/thread/128645972/choose-angle-graphics-backend-none-of-them-work-well?hl=en

But I don't see that on Linux:

![image](https://github.com/playcanvas/engine/assets/5236548/163ec7f2-8995-4286-86a9-29dac3d1c614)

Can anyone test to use another backend via `chrome://flags/`?

**Comment by LeXXik** [comment]
@kungfooman I tried switching 116 to OpenGL backend on Windows - it is much faster:

![image](https://github.com/playcanvas/engine/assets/5677782/2c5d6385-f885-40ce-a567-c7899512c871)

However, I believe Chromium team has already identified that the issue is related to DX.

**Comment by kungfooman** [comment]
> However, I believe Chromium team has already identified that the issue is related to DX.

Cool, I just saw the multisampling commit/fix, but I guess that narrows it down anyway then. Can you make a screenshot of that backend option (because I can't see/find it)?

**Comment by Maksims** [comment]
> @Maksims - can you please confirm this is Chrome 115 issue as well.

Yes, used Version 115.0.5790.110
Switching ANGLE to OpenGL as @LeXXik suggested reduced compilation times 5 times.

**Comment by kungfooman** [comment]
Anyone with access to Chrome on Window: is there a dxcompiler.dll in Chrome, or... with a PE depedency analyzer (e.g. [Dependency Walker](https://www.dependencywalker.com/)), does it load this dxcompiler.dll?

![image](https://github.com/playcanvas/engine/assets/5236548/0c85e7c8-8f84-4d57-848e-a59270b55468)

Then it should be easy to just download a few .zip releases and test until it is fast again... this wouldn't require any compilation/linking, just .dll swapping, so should be quite fast to tackle it down.

**Comment by kenrussell** [comment]
@mvaligursky and others, please regularly test PlayCanvas on Chrome Beta, and ideally at least periodically on Chrome Canary. If a regression like this makes it into Chrome Stable, it is generally not possible to fix quickly.

I hope that it will be possible to integrate the fix for this issue into Chrome 116. See https://chromiumdash.appspot.com/schedule .

**Comment by mvaligursky** [comment]
Chrome 116 is out .. is somebody able to confirm the fix is in and working? I don't have access to my Windows machine for the next couple of weeks unfortunately.

**Comment by leonidaspir** [comment]
Oh yes, I don't have times but it's pretty obvious under v116 aritelia.io is super fast to compile its shader once again.

**Comment by mvaligursky** [comment]
Fantastic, thanks @leonidaspir . 
I'll close the ticket, but please reopen it if this still fails in some cases.
