### ISSUE TITLE
Critical dependency: the request of a dependency is an expression - /webgpu/webgpu-graphics-device.js

### ISSUE THREAD

**Issue by AlbertoMalavasi** [playcanvas/engine#5730]
Title: Critical dependency error in playcanvas module with webpack

**Issue description**

When building my project, webpack throws a critical dependency warning associated with the playcanvas module. 

The warning states

```
WARNING in ./node_modules/playcanvas/build/playcanvas.mjs/platform/graphics/webgpu/webgpu-graphics-device.js
Critical dependency: the request of a dependency is an expression
```

**Steps to Reproduce**

```

import * as pc from 'playcanvas';

export default class ViewerManager {

    constructor() {
        console.log(pc)
    }
}
```

**Environment**

Node: ^16.0.0 || ^18.0.0
npm: ^7.0.0 || ^8.0.0 || ^9.0.0
playcanvas version: 1.66.0
webpack version: ^5.76.3

**Expected behavior**

The project should build without any critical dependency warnings.

**Actual behavior**

Webpack throws a warning regarding a critical dependency issue in the playcanvas module.

**Comment by kungfooman** [comment]
Thank you for pointing it out!

Happens since https://github.com/playcanvas/engine/pull/5711

We should stick to `document.createElement('script')` in src/platform/graphics/webgpu/webgpu-graphics-device.js

In addition to this webpack issue, we can also no longer use relative paths because of `import`.

**Comment by LeXXik** [comment]
I believe it is due to those 2 lines:

https://github.com/playcanvas/engine/blob/3fc8bf0ef9b50b32335cd5c7cc0718eaaf1eb7ed/src/platform/graphics/webgpu/webgpu-graphics-device.js#L169-L172

Here the guys suggest to explicitly convert to string:
https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

However, it sounds like a webpack issue? Not sure the engine should support it, as it has chosen rollup.

**Comment by kungfooman** [comment]
> However, it sounds like a webpack issue? Not sure the engine should support it, as it has chosen rollup.

We have to be agnostic about that, the engine (ESM files in npm package) are consumed by third-party bundlers to create a user bundle

**Comment by mvaligursky** [comment]
Any thoughts on this @slimbuck ?

**Comment by mvaligursky** [comment]
We have a mentioned of it here: https://forum.playcanvas.com/t/engine-release-v1-66-0/33297/3

**Comment by slimbuck** [comment]
The previous method of loading glslang with a script tag was actually loading a 'loader script' which performed the dynamic import (see [here](https://github.com/playcanvas/engine/pull/5711/files#diff-4f69e6ebbf40c59abf968e09d0eaddfd191b443485d3a0d4d9310a0e5dd94e9dL159)).

The loader script was downloading the actual wasm glue script via CDN (unacceptable) and using a dynamic import statement anyway (though it included the webpackIgnore comment and so worked with webpack).

So it seems we have two options to address this issue:
- add `/* webpackIgnore: true */` to the import statement and update tooling to keep the comment (by default comments are stripped)
- use the string approach found by @LeXXik above

The second option is the simplest and least invasive.

Can anyone test that the following works correctly with webpack?:
```javascript
        const results = await Promise.all([
            import(`${twgslUrl}`).then(module => twgsl(twgslUrl.replace('.js', '.wasm'))),
            import(`${glslangUrl}`).then(module => module.default())
        ]);
```

**Comment by kungfooman** [comment]
> Can anyone test that the following works correctly with webpack?:

Just tested and it definitely works (red: as it is currently, green: with your fix):

![image](https://github.com/playcanvas/engine/assets/5236548/6787a5b2-c795-49f7-b224-6547494b44fc)

**Comment by slimbuck** [comment]
Lovely - thank you so much! I'll merge the fix then.

**Comment by pavle-goloskokovic** [comment]
The issue still happens if webpack tries to use prebuilt es5 playcanvas engine (`node_modules/playcanvas/build/playcanvas.js`) instead the default mjs.

One possible solution is to add [`noParse`](https://webpack.js.org/configuration/module/#modulenoparse) option to the `module` section of your webpack config:

```javascript
...
module: {
        ...
        noParse: [
            // ignore imports and requires in playcanvas build
            /playcanvas\./
        ],
        ...
}
...
```

**Comment by kungfooman** [comment]
Wow, what a chain of issues rewriting that dynamically added `<script>` to `import`, thank you for reporting - it makes sense, since template strings are transpiled.

Can't you use ESM version aswell if you put `{type: "module"}` in your `package.json`? Transpiling down to ESM should be easy, while you can't "up-transpile" the ES5/UMD version to ESM.

**Comment by marklundin** [comment]
It's likely this [script import](https://github.com/playcanvas/engine/blob/main/src/framework/handlers/script.js#L151) will be cause this issue as well.

**Comment by pavle-goloskokovic** [comment]
> Can't you use ESM version aswell if you put `{type: "module"}` in your `package.json`? Transpiling down to ESM should be easy, while you can't "up-transpile" the ES5/UMD version to ESM.

@kungfooman I use Typescript so using default ESM import works, but my output target is ES5 and I import prebuilt ES5 version of the playcanvas engine to avoid needing to recompile entire playcanvas source code on each update during development and when creating production builds.

**Comment by Mistale** [comment]
We're in the same boat as @pavle-goloskokovic . While we can use ESM in our projects, it would require us to turn on transpilation of dependencies in `node_modules` ensure that we can still support ES5.

In our case, webpack tries to resolve the dynamic imports at build time and spits out hundreds of errors stemming from files within the ESM-module folder of the playcanvas package.  The `noParse` trick works well, but we would prefer if the issue could be solved on the playcanvas side rather than requiring downstream projects to use special webpack configurations in order to get the commonjs version to work with webpack.

**Comment by mvaligursky** [comment]
@marklundin is just cooking this one, any feedback?
#6090
