### ISSUE TITLE
[Issue] Reparenting entities

### ISSUE THREAD

**Issue by redsparkzone** [playcanvas/engine#576]
When you move the entity from one parent to another in the editor, it maintains its local transform (relative position, rotation and scale), which is not convenient in my opinion.

For example, imagine the old parent has some weird transform setup, like scale (10, 5, 20), and the child entity has the local scale (0.1, 0.2, 0.05) to counter that up. Now when we move that entity to the new parent with (1, 1, 1) scale, it becomes much smaller relative to the world, and needs readjusting to (1, 1, 1) to achieve parity. Same goes for position and rotation.

I propose the entity should maintain its global transform when being moved from one parent to another **in the editor**.

**Comment by phindle** [comment]
"I propose the entity should maintain its global transform when being moved from one parent to another in the editor."

did you mean say "I propose the entity should **_reset_** its global transform.."?

**Comment by redsparkzone** [comment]
I mean it should stay the same relative to the world (i.e. top root node in the scene), but should change relative to the parent. Transform displayed in the editor is currently relative the parent - and it should readjust itself based on the new parent transform.

**Comment by Maksims** [comment]
Why not get world transform of entity before reparenting, and then set it back when reparented?
Scale actually won't work generally, as there is no such thing as global scale. Which means that there are ways to have parents scaled so that other parent scaled differently, your entity will looked skewed differently, and there is no way to compensate that using local scale of reparented child.

Changing current behaviour won't be possible, as it will change general logic on which many apps relied on, so it will break. Alternative function or argument for reparenting method is potentially possible way to go with it.

**Comment by redsparkzone** [comment]
Are we talking about in-editor reparenting or in-code? I'm totally fine with in-code reparenting as it is. My concern was only about in-editor reparenting!

**Comment by willeastcott** [comment]
Hmmm, I kinda agree with @redsparkzone, here. Or make it an option. Like ALT+drag locks the world space position of the reparented entity.

**Comment by Maksims** [comment]
If this is an Editor feature, then it shall be discussed in forums http://forum.playcanvas.com/c/suggestions
Github is for engine-only stuff.
