### ISSUE TITLE
[Examples] The example name does not get used

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5832]
The examples specify name using the NAME property, but it does not seem to get used, and the name is based on the module name instead.

Repro:
- change the name
<img width="249" alt="Screenshot 2023-11-20 at 11 45 02" src="https://github.com/playcanvas/engine/assets/59932779/91ecb90c-54ab-4576-b5a1-9313fa23d000">

- rebuild / reload the example and observe the name is not changed:
![Screenshot 2023-11-20 at 11 45 41](https://github.com/playcanvas/engine/assets/59932779/ca3cb3ee-b308-4c2a-bb65-1d8343282d8f)

**Comment by mvaligursky** [comment]
@kungfooman for visibility

**Comment by kungfooman** [comment]
Hey @mvaligursky, thank you for raising the issue!

I contemplated a bit and I'm not what the best action here is.

When I rewrote the examples I noticed some irregularities in the naming convention, for example:

https://github.com/playcanvas/engine/blob/2bf47b09493675b41f596b8d7cfecc790e35aa54/examples/src/examples/graphics/area-lights.tsx#L4-L7

https://github.com/playcanvas/engine/blob/2bf47b09493675b41f596b8d7cfecc790e35aa54/examples/src/examples/graphics/clustered-area-lights.tsx#L6-L9

1) Some classes share the same name causing potential confusion or bundler `Example$123` issues
2) Only `static NAME` property is changing the name

So it made sense to simply use the "real" class name to keep it easy and be on the safe side and it also creates ESM class name alignment.

But I can also see the pattern here, that this is maybe what you want:

 - Name: Clustered Area Lights -> `class AreaLights`?
 - Name: Reflection Box -> `class BoxExample`?

So I pretty much see four options:

1) Keep `static NAME` as it is, maybe someone requires it for something
2) Remove `static NAME` altogether as a leftover/relic from old build system
3) Display `static NAME`, but don't make it act like a slug
4) Display `static NAME` and make it act like a slug aswell

I tend to (2) since it's less code that could go wrong, whereas (3) and (4) add more code and a bigger generated `example-data.mjs` which also could lead to naming conflicts if we just copy/paste an example and forget to update `static NAME` :thinking:
