### ISSUE TITLE
Issues with transparency in glb models

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5902]
I tried few meshes with transparency, and it seems from some angles (depending on the sorted order) we don't render them correctly. 

Example: https://sketchfab.com/3d-models/glass-kettle-3f646a36c0a142cfa451af70357f4235#download

Correct:
<img width="628" alt="Screenshot 2023-12-19 at 11 12 11" src="https://github.com/playcanvas/engine/assets/59932779/01d192d3-08b4-41c9-bdde-28e5b770249f">

Incorrect from behind:
<img width="572" alt="Screenshot 2023-12-19 at 11 12 39" src="https://github.com/playcanvas/engine/assets/59932779/69f0024b-83a1-477e-a05e-9504bef25756">

Could be related to recent change to update depth with some transparent pixels (https://github.com/playcanvas/engine/pull/5705), but could be something else too.

Another model with similar but different issues: https://sketchfab.com/3d-models/ship-in-a-bottle-9ddbc5b32da94bafbfdb56e1f6be9a38

<img width="1049" alt="Screenshot 2023-12-19 at 11 14 37" src="https://github.com/playcanvas/engine/assets/59932779/1b72a228-0811-40ba-a58d-67ad7dde85e3">

**Comment by slimbuck** [comment]
Might be worth also comparing these models with three/babylon as sketchfab might be doing something custom.

I suspect you're right that the change in alpha is the cause here. Depending on the scene, you probably want either the old way or new way. (The new method results in some scenes rendering significantly better).

Do you think we should revert? Perhaps user could be given the option?

**Comment by mvaligursky** [comment]
Yeah I checked and other engines render this fine - that's why I created the issue.

I think we should expose some control over it. The change adds nice advantage in some cases. Maybe just a loading option for the container? That could be too inaccessible though.
