### ISSUE TITLE
Add method for Node

### ISSUE THREAD

**Issue by AlexAPPi** [playcanvas/engine#6317]
Now there are 2 methods available, setPosition and setRotation, I suggest adding 1 more method setPositionAndRotation.

public setPositionAndRotation(position: Readonly<pc.Vec3>, rotation: Readonly<pc.Quat>): void;

* This will further optimize position and rotation manipulations

**Comment by LeXXik** [comment]
I think we have an equivalent, or at least it is similar:
```js
entity.getWorldTransform().setTRS(position, rotation, pc.Vec3.ONE);
```

**Comment by Maksims** [comment]
A much bigger optimization many miss is to use `setLocalPosition` instead of `setPosition` where possible.

**Comment by kpal81xd** [comment]
@AlexAPPi So ive done some performance testing in #6625 and it doesn't seem like the performance gain is reasonable enough to warrant adding this method right now. If this issue was created for a personal project the chances of optimizing other areas would be much more successful that attempting to include this
