### ISSUE TITLE
Re-loading cubemaps fail to load associated textures

### ISSUE THREAD

**Issue by Astra307** [playcanvas/engine#6358]
When re-loading a cubemap asset that has already been loaded once before (with the standard asset loader) it fails to load the associated texture files, leading to errors and failure to compile when applying it to the scene. The first time a cubemap is loaded however, it also loads the texture files automatically, and there's no hiccups applying it to the scene.

See [this forum post](https://forum.playcanvas.com/t/re-loading-cubemap-fails/35801) for a more detailed description.

**Comment by slimbuck** [comment]
Do you have a simple repro case?

Looks like there should be a very simple fix for this. On the following line:
https://github.com/playcanvas/engine/blob/main/src/framework/handlers/cubemap.js#L294

`onLoad()` should be calling `processTexAsset()` instead (since `processTexAsset` checks the asset is loaded before continuing).

**Comment by Astra307** [comment]
Sorry I didn't make one..
Thx for fixing it anyways!!
