### ISSUE TITLE
Question on multi-app

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6388]
There was a question on Discord, so decided to put it here, as I am not sure if it is an error. If you change the multi-app example to start with two WebGL2 instances, only the last one starts. Is this an expected behavior? If set to WebGPU - both apps start normally.

![image](https://github.com/playcanvas/engine/assets/5677782/85a87828-ff3e-4dc7-8525-be20fe7fdac5)

![image](https://github.com/playcanvas/engine/assets/5677782/aad4289a-04d7-4833-a916-cb8c6d9564b4)

**Comment by kungfooman** [comment]
Definitely fishy and it starts working if you don't make all the code dependent on the single font asset.

Why don't make the cube rotate just because the font isn't loaded?

You can remove lots of intendation that way aswell, it only requires this:

```js
    app.on('update', (/** @type {number} */ dt) => box.rotate(10 * dt, 20 * dt, 30 * dt));
    assetListLoader.load(() => {
        textOutline.addComponent('element', {
            pivot: new pc.Vec2(0.5, 0.5),
            anchor: new pc.Vec4(0.5, -0.2, 0.5, 0.5),
            fontAsset: assets.font.id,
            fontSize: 130,
            text: text,
            color: new pc.Color(1, 0.9, 0.9),
            outlineColor: new pc.Color(0, 0, 0),
            outlineThickness: 1,
            type: pc.ELEMENTTYPE_TEXT
        });
    });
```

But I think it should work anyway, so something seems to cause issues when loading two assets at the same time, maybe some kind of static variable reuse conflict?

**Comment by kungfooman** [comment]
I went a bit with RuntimeTypeInspector over this example and it also found Infinity calculations (because `1 / device.width` when I add/remove a bunch of WebGL2 apps). I don't know why it happens but when it happens it even continues triggering this error even though all apps are seemingly removed:

![image](https://github.com/playcanvas/engine/assets/5236548/f04543f7-e74a-435c-b2dd-556dd433e71f)

Add conditional breakpoint `device.width === 0` at `pc.ForwardRenderer.prototype.setSceneConstants` (double click evaluated function in F12/DevTools)

Also happens in https://playcanvas.github.io/#/misc/multi-app (a bit older, still does WebGL1, but same issue)
