### ISSUE TITLE
Ability to merge multiple meshes into one

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#675]
It would be useful if the engine was able to merge multiple meshes together. To begin with, a single function could do the job. But beyond that, support in the engine to tag entities as 'static' and then do this kind of optimization automatically to reduce drawcall count, could be very handy.

**Comment by mrLoganite** [comment]
Tagging entities as static sound like a good way of doing it. I might also be a good idea to incorporate the light mapping as well as it highly likely the shadows on static objects would also want to be baked.

**Comment by guycalledfrank** [comment]
API thoughts:
Marking as static manually might not give desired granularity, e.g. you can end up having objects from different parts of the world stitched together - the resulting mesh will be hard to cull.
Instead what if you:
- add desired objects as children to some other object;
- add some "Combine meshes" component to the top object;
- It works.

Tbh, this is exactly what I was doing in Unity because of the culling reasons.

**Comment by daredevildave** [comment]
I like the idea of adding a parent component to combine meshes. But doesn't it have the same problem? You can still have two children that are 1000m apart.

**Comment by guycalledfrank** [comment]
You can but it's your (user's) fault then.
Additional idea: use similar logic (parent component) to combine multiple identical objects with hardware instancing.

**Comment by guycalledfrank** [comment]
Problem: can't easily combine lightmapped models, because each has their own texture/UVs... can atlas multiple lightmaps into one, but not always possible (lightmaps can be too big already).

**Comment by guycalledfrank** [comment]
Let's say you add a component called "Mesh Batch". Options:

- Combine unique meshes into one (checkbox, default=true). "Unique" means that there are no mesh instances with the same mesh. In the end scene.drawCalls will have one meshInstance instead of the original source meshInstances. Exception: if can't fit all instances into one new (16 bit) buffer, more than one mesh (and instance) will be generated.

- Combine repeating meshes (those which share the same mesh). Options:
-- Single mesh: same as with unique;
-- Static instancing: use hardware instancing, prepare instance buffer once, don't touch later. Falls back to Single mesh, if instancing is not supported;
-- Dynamic instancing: use HW instancing, but allow moving objects inside the group. Falls back to no instancing.

**Comment by willeastcott** [comment]
Hey, @guycalledfrank, does current batching support in the engine warrant closing this issue? Seems so to me.

**Comment by guycalledfrank** [comment]
Yes
