### ISSUE TITLE
Unable to use VertexIterator if VertexBuffer is used by TransformFeedback

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#6781]
It is not possible to use VertexIterator for the buffer if it is used by TransformFeedback.

The use case: particle system, with simulation using TransformFeedback, with occasional sets of some data to "create" particles.
If attempt to modify, it will fail with: `GL_INVALID_OPERATION: A transform feedback buffer that would be written to is also bound to a non-transform-feedback target, which would cause undefined behavior.`

What would be a correct way to read and write back data to buffers that are processed by TransformFeedback?

Example project: https://playcanvas.com/project/1233506/overview/tf-particles
Launch, and click on screen to try to use VertexIterator.

**Comment by mvaligursky** [comment]
You could read from the buffer, if you copy it back to the CPU (we do not have an API for it as this is not a common path).
But you cannot write to the buffer as the following transform feedback execution would override it anyways. You need to write to the source buffer, and not the target buffer.

You could copy the output buffer using something like this
```
const feedbackData = new Float32Array(bufferSize); // bufferSize is the size of your buffer
gl.bindBuffer(gl.ARRAY_BUFFER, feedbackBuffer);
gl.getBufferSubData(gl.ARRAY_BUFFER, 0, feedbackData);
```

But this would be a blocking operation, the CPU having to wait for the GPU to finish the processing, which could be very costly, as the GPU is typically running a frame or so behind, so possibly a whole frame would need to be rendered.

Typically, transform feedback is one way operation, where the result is consumed on the GPU only.

I'll close this for now, as we're not planning to add this as a feature due to the limitations, but do reopen if you need more help here.
