### ISSUE TITLE
Quaternion conjugate is missing from docs

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6878]
As per title, `Quat.conjugate` is missing from docs.

**Comment by willeastcott** [comment]
Why do you need it?

**Comment by LeXXik** [comment]
Personally, I use invert, but some articles use conjugate term. Since the method is in the class, thought it would make sense to expose it. Otherwise, why is it not inlined in invert?

**Comment by willeastcott** [comment]
> Otherwise, why is it not inlined in invert?

Because it's currently an internal function that doesn't seem super-useful to end users of the API. However, I wouldn't inline it because it's useful for people to look at the implementation of `invert` and see its a conjugation following by a normalization. Anecdotally, the Unity API chooses to expose an `Invert` but no `Conjugate`.
