### ISSUE TITLE
Loading skyboxes with pc.Scene#setSkybox fails to display cubemap

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#725]
Check out this project:

https://playcanvas.com/project/419976/overview/skybox-scripting

It uses pc.Scene#setSkybox to apply a cubemap. Press 'S' key to cycle cubemaps (there are 4).

IBL works, but the cubemap fails to display as the background. This only happens if Mip (in Render Settings of the Editor) is 1.

@guycalledfrank thinks this is more likely to be an asset loading issue, hence with I'm assigned it to you for now @vkalpias - reassign if you think someone else is better suited. :smile:

**Comment by guycalledfrank** [comment]
Skybox is being rendered, but it has a black cubemap applied, with 4x4 faces...

**Comment by vkalpias** [comment]
This is because we only load the faces of a cubemap if `loadFaces` is true in the cubemap asset. That boolean seems to only be set inside the `pc.Application` when we apply scene settings. There we check if the scene's skyboxMip is 0 and in that case we set `loadFaces` to true. This does not happen when we call `pc.Scene#setSkybox` which is unaware of the assets and the framework.

The easiest way to fix this would be to expose a boolean field on the cubemap asset which lets us force loading of cubemap faces. Otherwise we need to refactor how this works so that the cubemap loader itself knows when or when not to load the faces. That would tie the cubemap loader with the current scene which might be a little awkward.

**Comment by Maksims** [comment]
Using `this.app.setSkybox(asset)` - fixes the issue, and is preferable to be used.

**Comment by ImmanuelSamuel** [comment]
I tried using 
```
app.assets.loadFromUrl("/dds/space1.dds", "cubemap", function (err, asset) {
    app.setSkybox(asset);
}); 
```
However I get the following error
```
VM6889 pcdev.js:5097 Uncaught TypeError: Cannot read property '0' of undefined
    at GraphicsDevice.uploadTexture (VM6889 pcdev.js:5097)
    at GraphicsDevice.setTexture (VM6889 pcdev.js:5249)
    at GraphicsDevice.draw (VM6889 pcdev.js:5319)
    at ForwardRenderer.drawInstance (VM6889 pcdev.js:9585)
    at ForwardRenderer.renderForward (VM6889 pcdev.js:10091)
    at ForwardRenderer.render (VM6889 pcdev.js:10434)
    at Application.render (VM6889 pcdev.js:19194)
    at VM6889 pcdev.js:19504
```
and as mentioned the following gives me black cubemap. If I comment this out I get the camera clear color.
``
app.assets.loadFromUrl("/dds/space3.dds", "cubemap", function (err, asset) {
    app.scene.skybox = asset.resource;
}); 
```
