### ISSUE TITLE
Blur unfilitered shadow in lightmap space instead of baking VSMs

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#734]
Huge memory savings.

**Comment by willeastcott** [comment]
@mvaligursky What would you like to do with this issue?

**Comment by mvaligursky** [comment]
We're now using a shadow map cache during VSM blur, and so only allocate small number of those targets .. the memory impact is likely not that bad. 

But I'd prefer we implement some other solution of soft shadows instead of doing the blurs. Perhaps https://github.com/playcanvas/engine/issues/2815.

I'll close this ticket for now.
