### ISSUE TITLE
Add glTF loader to the engine

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#806]
glTF seems to be getting some traction. Let's add an importer.

**Comment by Maksims** [comment]
Been thinking about this format and how it could fit for engine-only as well as developers with Editor, and can see two major things:

1. **Engine-only** users would benefit a lot by simply being able to load this format. This does imply that file is treated as container and there would be easy and nice way to interact with contents (mesh information, animation, texture, material and other data). This would simplify life for engine-only users, and would allow users to simply plug'n'play their content using only Engine.

2. **Tools Workflow** (Editor) would be different. In order to provide users with full control over their assets: textures and their parameters, materials and their properties as well as being able to process their models, like auto-unwrap. And most importantly allow developer to compress textures to generate variants. This all implies that glTF would be treated as container format, just like FBX is, and would be a source for all target assets listed above. This would allow easy workflow of simply dragging stuff into Editor, as well as fine-control of it's content once it is imported. Re-importing would work same as FBX, updating stuff as required.

**Comment by willeastcott** [comment]
But glTF is designed to be a format for transmission and loading. i.e. it's a runtime format, not a source format, as FBX is. It is worth evaluating whether it could be used as a replacement for PlayCanvas' current JSON format.

**Comment by sonygod** [comment]
how about glTF 2.0 format? why not support that? or may be you consider some business  reasons  for your online editor.

current playcanvas only support their owners   json format ,so it's size is not well for web  transmission and loading if scene or model size is huge.

**Comment by willeastcott** [comment]
Yes, a glTF importer would indeed support 2.0 since that is the current head version of the format.

Do you have evidence that GZIPd PlayCanvas JSON is much different in size to glTF? Personally, I think the benefit of glTF is probably more about it being faster to read and lower memory requirements on the client.

**Comment by willeastcott** [comment]
@daredevildave Since you've now merged the OBJ parser, should we put a glTF parser in the same folder? The question is: Should parsers be part of the core engine or separate? Just concerned about bloating the engine.

**Comment by daredevildave** [comment]
Yes, glTf load would go in the same place.

The obj parser is *not* included in the engine (it's not in the dependencies list) because it is not necessary for developer's to use this (obj's should be converted into json via the Editor pipeline). I would probably go the same path with glTf unless we plan to make glTf files available as runtime assets from the Editor.

**Comment by willeastcott** [comment]
Shouldn't the parsers go in extras then?

**Comment by Maksims** [comment]
Providing native support for glTF in engine will enable engine-only workflow so developers wont need to go through Editor to export models.

**Comment by willeastcott** [comment]
Indeed. 😄

**Comment by willeastcott** [comment]
For anyone coming to this issue looking for glTF support, please head here for a fully-featured glTF 2.0 loader:

https://github.com/playcanvas/playcanvas-gltf

We might transfer the loader to this repo at some point. But for now, we'll keep it as a separate extension that you can drop into your projects.
