### ISSUE TITLE
Elements: changes to layout mechanism

### ISSUE THREAD

**Issue by yard** [playcanvas/engine#817]
Hi guys,

Learning from my mistakes :)

This issue is to discuss elements' layout update I suggested in https://github.com/playcanvas/engine/pull/816.

The idea is to have the following concepts of layout modifiers:

- Anchors: left, bottom, right and top fractions in **parent** coordinate space which drive the bounding box of an element
- Corners: left, bottom, right and top offsets of corresponding element edges from anchors
- Pivot point: the origin of local transforms in **current element** coordinate space.

This "complication" comes in necessary to fluently support all possible layout variants, namely: dynamic width/height, fixed width/height, dynamic width/height with paddings, offsetting the element from anchor-driven position.

Pivot point is further separates transforms from element's positioning to allow for the things like rotating around an edge/corner, dynamic offsets etc.

The existing system of anchors and pivot offsets seems limited to me: for instance, it's quite difficult to make a button that takes 100% of the width and has 10px padding around it. Also, pivot point driving element offset makes animations (consider flipping animation) clash with position offsets – still doable, of course, but user code becomes more complicated.

The last but not least: this system is a "copy" of Unity's UI system that seems to be performing quite well – so why not re-use it? :)

@daredevildave please let me know if the above explanation makes sense to you and I will prepare a PR for this part of the original pull request.

**Comment by daredevildave** [comment]
I believe you can accomplish all this already using the left/right/top/bottom properties.

In your example something like this:

```
this.entity.element.anchor = [0,0,1,0]; // minX = 0, maxX = 1
this.entity.element.height = 100;
this.entity.element.left = 10;
this.entity.element.right = 10;
```

**Comment by yard** [comment]
Technically you are suggesting the right thing, but the devil is in certain details, as usual.

I've been playing with master branch on that and found a few issues with the current implementation:

- Anchor offsets aren't stored explicitly anywhere, and rely on properties like _width and _absLeft upon setting/retrieval. The most obvious implication is this code:
```
panel.addComponent('element', {
    anchor: new pc.Vec4(0, 0, 1, 1),
    pivot: new pc.Vec2(0.5, 0.5),
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    type: "image",
    textureAsset: panelAsset
});
```
Which will not work (as there might be no parent yet or the width might not computed) – please mind I did fix element/system.js to pass these props on before testing it :)
- For some reason pivot point also takes part in this computations. While I do appreciate it might be a "by design" thing, I still believe it's much more reasonable to separate layout box (driven solely by anchors and corners) from pivots and transforms: you don't want to mix those and surely you don't want changes to transforms (for animation purposes) affect the layout box.
- Setting pivot point changes position, which means pivot does something other properties do. If you want to change the position, why don't you change anchors/left/top/bottom/right? And it's not about pivot being relative to the size of an element – the former properties do allow for that as well.
- Minor, but still: you use a single property for anchors, but went for 4 properties for corners and that's why I introduced borders property. Just being consistent, you know :)

**Comment by yard** [comment]
Hey @daredevildave,
Sorry to bother you during holidays – but maybe you have any comments on the above?

**Comment by daredevildave** [comment]
Sorry, I'm not back into the office until next week. So I'll be taking a proper look then.

Perhaps we are working from a different basic idea, but I don't really understand your suggested changes. 

With respect to pivot and localPosition. You say: "how do I modify localPosition once pivot is set?" In the current system, the local position is the position of the pivot point with respect to the parent. To position an element you just call setLocalPosition(). If you move the pivot the then local position is unchanged, but the element moves (for example if I move pivot from left edge to right edge an image element would move left by one width).

Changing the values of "left", "right", "top" and "bottom" changes the width, height and local transform. Imagine the pivot point is on the left edge, and I change the value of "left". By definition the local transform must change because the left edge (where the pivot point is) has moved. How do you propose separating pivot from position?

There are 5 properties which define an element's size and position: x,y,z (local transform), width and height. The corners or left, right, top, bottom can all be expressed in terms of these properties.

And by the way, as I understand it. The existing system is very similar to Unity's UI already?

**Comment by yard** [comment]
Hi,

No probs – holidays are holidays :)

First of all, in your example ("for example if I move pivot from left edge to right edge an image element would move left by one width") – I think that's the issue. You are moving pivot and thus change the position of the element. But why? You already have anchors and top/left/right/bottom affecting the position. Wouldn't it make more sense for the pivot to define the origin for transforms, and leave positioning (sans localPosition, of course) and sizing to layout mechanism?

Changing local transform with modifying left/top/right/bottom means you lose the flexibility to animate elements as local transform might be "dirty" making it difficult to animate the element to/from designed position. What I propose is to keep local transform operating "around" pivot point and make it be identity unless modified explicitly. This way you design the interface by placing elements and then animate to show, hide, rotate and do whatever you'd like. Resetting local transform to identity will put the element back and that's it.

Also, you aren't entirely correct re width and height driving positioning: width and height can be computed from corners, but not the other way around. The easiest example is an element without a parent: having undefined width and height it can still ask for specific corner values, and this shouldn't be a problem.

As for being very similar – as I said, the devil is in the details, and I just propose to eliminate these details :)

**Comment by yard** [comment]
Hey @daredevildave, sorry to bother you - any thoughts on the above?

**Comment by daredevildave** [comment]
OK, I've been looking into this a bit more.

Using corners property and using that to calculate width/height could make sense. Though in your example (no parent) your code has invalid width and height so it's seems to just trade one issue for another.

I'm still not sure if I'm missing the point of your suggestion around pivot point, but I'm still pretty confused over what you gain.

![screenshot_18_01_2017__11_39](https://cloud.githubusercontent.com/assets/504980/22062670/c6c87770-dd72-11e6-99b9-a3e4a9b43f0f.jpg)

The local position is (0,0,0) but because of the corners the pivot point is now at (64,64,0). This just seems wrong and means we would need another property to expose the pivot point. Why introduce another position?  I haven't seen a concrete example of a use case where the current system doesn't work.

Using the Unity UI as a preview. How would you set up the example in screenshot above in Unity. It doesn't seem like it is possible to me?

![unity_5_5_0b11_personal__64bit__-_untitled_-_test_unity_project_-_pc__mac___linux_standalone__personal___opengl_4_1_](https://cloud.githubusercontent.com/assets/504980/22062878/e4ac8000-dd73-11e6-86bd-b29d8c15059f.jpg)

It looks like this (as I would expect).

**Comment by yard** [comment]
Re invalid width / height – my point here was that the position of the element should be defined by corners and anchors, **and should not depend** on the presence of parent. What's wrong with creating a button, telling it to take full parent rect sans 10px marging, but adding it to the parent rect later?

Re pivot: technically the same applies here. If we lay elements out using anchors and corners, why would the positioning depend on the pivot? Consider two screenshots from Unity illustrating exactly this:

1. Pivot at bottom left corner: https://www.dropbox.com/s/od14ng22sn51p3u/Screenshot%202017-01-18%2018.47.35.png?dl=0
2. Pivot at top right corner: https://www.dropbox.com/s/x0fyh2059agq18c/Screenshot%202017-01-18%2018.47.45.png?dl=0

As you can see moving pivots around doesn't change the corner or anchor values, neither does it move the component (disregard float precision errors in the inspector).

The results of rotations, for instance, would, however differ for both cases:
1. Pivot at bottom left corner: https://www.dropbox.com/s/cczbodsv7oqnxx5/Screenshot%202017-01-18%2018.49.39.png?dl=0
2. Pivot at top right corner: https://www.dropbox.com/s/i4vgzwmrf7jzdkm/Screenshot%202017-01-18%2018.49.55.png?dl=0

And this is totally fine (I think): you lay your interface out using corners and anchors full stop; then you move pivot point as you wish and tune local transforms to animate things, tweak the position etc.

I should admit, however, the local position does get changed when pivot moves around – my mistake; but mind one wouldn't normally modify local position of UI elements – again, you have rect transform for that (and that's why in Unity you don't even see it unless switched to debug inspector mode).

Hope this makes sense :)

**Comment by daredevildave** [comment]
OK, well I think we're getting closer to the same thing now :-)

In your pictures from Unity you can see that Unity is exposing the l/r/t/b values when the anchors are split and yes those values remain constant when you change the pivot.

PlayCanvas has the same behaviour. Set the the same values as above: 
```

**Comment by daredevildave** [comment]
OK, well I think we're getting closer to the same thing now :-)

In your pictures from Unity you can see that Unity is exposing the l/r/t/b values when the anchors are split and yes those values remain constant when you change the pivot.

PlayCanvas has the same behaviour. Set the the same values as above: 
```
pivot: [0,0]
anchor: [0.35,0.35,0.65,0.65]
```
then set `element.left = 30; element.right=30;element.top=30;element.bottom=30;` and you will see the same behaviour. Changing the pivot point from 0,0 to 1,1 changes the local position but doesn't change the anchors or l/r/t/b.

**Comment by yard** [comment]
I might've missed smth in my tests, but I clearly remember that changing pivot point did move the element (although I didn't change anchor). Is it supposed to be like so?

**Comment by daredevildave** [comment]
The element will move because setting the pivot in code (`element.pivot = new pc.Vec2(1,1)`) doesn't change the local position. If you counter the pivot change by changing the local position (which is what the Unity editor does by default) then the element won't move.

e.g.

```
// start with pivot at 0,0

// move pivot without moving element
entity.element.pivot = new pc.Vec2(1,1);
entity.translateLocal(entity.element.width, entity.element.height, 0);
```

**Comment by daredevildave** [comment]
So, what I'm going to do...

I'm currently looking into how to best store these values internally (e.g. possibly replace width/height with corners property). So that you can assign all values successfully before adding to the hierarchy. 

But I believe the rest of the behaviour is correct (and consistent with how you expect it to behave). I'll try and put together a test page so that we can fiddle some numbers and check everything is behaving as expected.

**Comment by daredevildave** [comment]
Take a look at this: https://s3-eu-west-1.amazonaws.com/ui-layout.playcanvas.com/ui/positioning/index.html

It lets you fiddle with properties of a two element hierarchy.

**Comment by yard** [comment]
Hey,

Just did play with the page. Generally looks sane, but it looks like I don't quite get what's the purpose of pivot point in your example. It does move element around why corners property is unchecked (not sure what it means logically though) and doesn't seem to change position when corners are set. Positioning behaves the same – no change when element is driven by corners.

Is the behaviour expected or it's some sort of a bug?

**Comment by daredevildave** [comment]
Just merged [this change](https://github.com/playcanvas/engine/pull/843) which adds support for `margin` property (this the collection of left/right/top/bottom)

This fixes also lets you define all properties up front before you add element to the hierarchy.

I'm pretty much considering this a fix to this issue, but let me know if you think there are any more use-cases that don't work.
