### ISSUE TITLE
meshInstance.aabb may be out-of-date?

### ISSUE THREAD

**Issue by AsAddict** [playcanvas/engine#844]
Hello everyone, I am new to playcanvas and reading the source code these days..

`var aabb = meshInstance1.aabb;` 

Is this aabb out-of-date if i have changed its certain ancestor-node's local transformation before?

I guess I must call `meshIntance1.node.getWorldTransform()`  before to get the updatable boundingbox.

thanks!

**Comment by Maksims** [comment]
Perhaps worth to be mentioned in `aabb` property that it might be not up-to-date if any ancestor including self been transformed since last application render.

**Comment by mvaligursky** [comment]
It's possible the code has changed since this issue was opened, but it seems returned aabb is up to date, as internally it calls .node.getWorldTransform() which propagates world transforms old the way from root if needed.
If you for example change a position of matrix of the parent node, that would recursively mark all world matrices of children as dirty. Following call to getWorldTransform would then correctly evaluate them even if the transform properties of the node were not changed (and only parent was changed).
