### ISSUE TITLE
WebVR does not work on Chrome 56

### ISSUE THREAD

**Issue by renatoruk** [playcanvas/engine#859]
After updating mobile Chrome on Android to version 56, none of the examples on [the demo page](https://playcanvas.com/industries/vr) nor the WebVR project we are developing (it was forked from the base VR project) work anymore.

We need to use the WebVR functionality with third party headsets that do not have a clicker button, so the expected behavior is that the screen splits into two halves without the need to use the supported headset. (e.g. Daydream or Vive)

The error we're getting is `No VR display or headset is detected.`, although the same code worked on Chrome 55, just before the update.

I presume that the issue here is that WebVR is supported in Chrome 56, but since the headset is not actually connected, it shows the correct error.

**Comment by yaustar** [comment]
This is an issue that I'm currently looking into as it is currently affecting all WebVR demos that I've tried (three.js and the examples on webvr.info) do not work unless polyfill is forced.

Yes, you are correct that since Chrome 56 now has implemented the WebVR API, polyfill is no longer needed. The issue is that only a small number of devices (I'm assuming the Daydream supported devices) are deemed to a be a compatible display for use with WebVR.

**Comment by Maksims** [comment]
Just to clarify - this is due to polyfill assumed all mobile devices are VR capable. But WebVR has different assumptions about devices, so pretty much all non-daydream mobile phones didn't get VR love :)

Here is related issue on https://github.com/googlevr/webvr-polyfill/issues/177

**Comment by renatoruk** [comment]
@yaustar, @Maksims  thank you guys for clarifying this. Will follow the thread from now on. 

Do you plan on adding any modifications to the WebVR polyfill included in Playcanvas before the official fix is out?

**Comment by renatoruk** [comment]
Since Playcanvas source is not available through online code editor, where could I force usage of the webvr polyfill?

**Comment by Maksims** [comment]
You could override property on `pc.VrManager` which called `isSupported` to return `false` in cases where it is true but you still want to enforce polyfill to get loaded.

**Comment by daveranan** [comment]
I'm a bit confused, not sure if this is a bug or what not.
If you open any WebGL demo, i.e. [WebVR 360 Image](https://playcanv.as/p/v6qoi4Yt/) by itself in Chrome 56, VR & Gyroscope _do not work_. All you can do is tap/click & drag the screen to look around.

But, if you open any of tutorials page, i.e. [WebVR 360 Image Tutorial Page](http://developer.playcanvas.com/en/tutorials/webvr-360-image/), VR button & Gyroscope are fully functional and work perfectly like they were used to.

I connected my android phone to mac, inspected the page to see if there are any error differences, but there were none. Same errors.

Am I'm missing something here?

**Comment by yaustar** [comment]
It's a http/https issue. WebVR is only enabled on webpages that are on the [Origin Trial](https://github.com/jpchase/OriginTrials/blob/gh-pages/developer-guide.md) and only on https.

The tutorials pages are on http so WebVR isn't natively enabled and the polyfill is used instead.

So if you load http://playcanv.as/p/v6qoi4Yt/ (note it's on http), it will 'work'.

**Comment by daveranan** [comment]
Even as a web dev, I wouldn't have thought that https would be such an issue. Thanks for pointing that out @yaustar, have been trying to debug this all morning.

**Comment by daveranan** [comment]
Here's another bug, not really sure it's a bug or not. So I forked the 360 VR image [tutorial project](http://developer.playcanvas.com/en/tutorials/webvr-360-image/), and was expecting same results as on the tutorial project, but it just shows brown/red background in VR instead. Link: https://playcanv.as/p/2EMTn1Dv/

Also, why the User Experience is different on iOS devices vs Android? On Android you have option to turn on the VR. But by default you can use gyroscope to move camera around. On iOS it forces you to use phone in cardboard mode, otherwise it will not work.

**Comment by bjsommer** [comment]
Hi together,
thanks for this thread!
I experienced the same problem when using the samples from webvr.info:
https://webvr.info/developers/
When I used the standard version of the actual Chrome 56, the demos did not start.
But then I did the following: downloaded 
_Chrome Beta (58.0.3029.82)_
When I started the demos, I got a message that
_google vr services_ 
have to be installed. After I did this, all demos worked again :-)
In addition, I have of course the 
_Cardboard app (4.2)_
installed.

**Comment by daredevildave** [comment]
Hi @renatoruk, can you confirm if this is still an issue for you? And if so, on which devices?

There are differences in the way Android behaves on different devices. In particular Daydream-ready devices (Google Pixel phones) can handle WebVR natively, but other devices do not.

**Comment by renatoruk** [comment]
Hello @daredevildave, yes, webVR is functional now in Chrome 57 on Android. I tested on Samsung Galaxy S7 so it probably ran the polyfill version.

**Comment by Dhellblazer** [comment]
Hola, tengo un problema al ver contenido webVr en chrome 58 (Android), la imagen sale reducida a un cuadro muy pequeño en la parte inferior izquierda.

**Comment by Maksims** [comment]
@Dhellblazer does this happen to many WebVR demos as well as other engines/frameworks? If so, it is Chrome 58 regression bug, and should be reported here: https://bugs.chromium.org/p/chromium/issues/list

**Comment by Dhellblazer** [comment]
Hello everyone, as I mentioned earlier in Chrome 58 there is the problem that it does not load well the screen, because it comes reduced or only a part. With happiness I comment that the version 59 must leave the next week, at the moment you can download the Beta version, in this version (Chrome 59) the problem is solved. Thank you.

**Comment by developersmith1990** [comment]
Hi, i am newly on Playcanvas i have write below code in my editor, but when i am going to launch my project, and pressed key right its not working, anyone can check and tell me please, where i am wrong?
 
pc.script.create('move', function(app){
var Move = function (entity){
this.entity = entity;
};
Move.prototype = {
initialize: function () {
},
update: function (dt) {
if(app.keyboard.isPressed(pc.input.KEY_RIGHT)){
this.entity.translateLocal(0.1,0,0);

}
}
};
return Move;
});

Thanks
