### ISSUE TITLE
Make available on npm

### ISSUE THREAD

**Issue by timmak** [playcanvas/engine#932]
Would like to to be able to require the engine as a module.

**Comment by ronkorving** [comment]
Now that the `package.json` PR #931 has landed, you guys can publish this on NPM. Here's a quick [getting started guide](https://docs.npmjs.com/getting-started/publishing-npm-packages) on publishing packages on NPM. I hope we can use this soon :)

**Comment by tommhuth** [comment]
How's this coming along?

**Comment by willeastcott** [comment]
Last week, I published a test package to npmjs:

https://www.npmjs.com/package/eslint-config-playcanvas

I'm going to update the engine to use this package probably tomorrow and merge this ESLint update: https://github.com/playcanvas/engine/pull/1161

The outstanding things that we have to figure out:

- Do we start committing engine builds to GH?
- If so, where should they be built to? I think build instead of build/output
- Should we change the library build name? Currently, we build to playcanvas-latest.js. I think playcanvas.js (and playcanvas.min.js) are probably better.
- Do we need to update our continuous integration server in response to any of the above changes?

**Comment by Disorrder** [comment]
@willeastcott I'm using engine with Webpack. And this is only one library I should load from file :) I'd love to install it by npm with semver features. So,
 - you're not using requireJS or something like that, so of course you need to commit built version.
 - Doesn't matter folder name, just write in your package.json file `main`
 - playcanvas.js would be nice
 - you can also add job to your CI which will build and publish to npm each time you push to master (or specified branch)

**Comment by thisredone** [comment]
Any progress on this?

**Comment by injitools** [comment]
> Any progress on this?

npm i -S https://github.com/playcanvas/engine
