### ISSUE TITLE
depthWrite with add type alpha

### ISSUE THREAD

**Issue by sdfgeoff** [playcanvas/engine#944]
If you have an additive type material (blendtype: 1) then it will never write to the depth buffer, even if depthWrite: true.

Why would you want to? In my case I have a HUD that overlays on the scene. I sample the depth map to ensure a post effect does not overlay the HUD. If the HUD objects use additive type alpha, then the depth map does not know the difference between the HUD and the background.

**Comment by guycalledfrank** [comment]
Do you mean the readable depth buffer texture? Or a general zbuffer? How do you sample it exactly?

**Comment by sdfgeoff** [comment]
I use a screen filter and sample the texture. You can see the filter here:
http://www.6dof.space/Inferno0.0.2/Scripts/filter.js

**Comment by guycalledfrank** [comment]
Ah yes, I see. So we simply omit any blended draw calls for this depth map right now: https://github.com/playcanvas/engine/blob/master/src/scene/forward-renderer.js#L1904

I wonder what the best solution API-wise would be.
- Autoset drawToDepth when changing meshInstance material and allow further changes to it? Bad, because you can change the material itself, and meshInstance won't be notified.
- Just draw everything only based on drawToDepth? Bad, because there will be huge opaque surfaces at wrong places.
- add some kind of additional meshInstance flag, like forceDrawToDepth?

@willeastcott @daredevildave  @Maksims ?

**Comment by guycalledfrank** [comment]
Another way is just to make the posteffect system more flexible, so you can simply draw the HUD after the posteffect, what would be the proper options actually.

**Comment by sdfgeoff** [comment]
Yeah, it's tricky to handle depth map's with blended calls. I don't think there is any perfect solution

Rather than extending the posteffect system to allow the HUD to be drawn afterwards, I would prefer the ability to run multiple scenes at the same time, and the postFX to be applied on a per-scene basis.
This makes sense because the playcanvas interface already has methods of putting objects into scenes, so no UI development is required.

**Comment by OmarShehata** [comment]
I've run into this issue as well. I'm trying to create a water shader with a foam line. The water material has blending so that it can be translucent when `alphaToCoverage` isn't available. My approach to rendering the foam lines using the depth texture is similar to the one described here:

https://lindseyreidblog.wordpress.com/2017/12/15/simple-water-shader-in-unity/

Since blended objects are filtered out of the depth texture, I can't use this technique. @guycalledfrank of the options you listed, either of the last two would be perfect for my case. 

Are there any workarounds for now?

**Comment by willeastcott** [comment]
I would recommend bearing with us while we put the finishing touches to a major rework of the engine. You can find the current state of the PR holding this update [here](https://github.com/playcanvas/engine/pull/1057). After we deploy this, I suspect it'll be much easier to do what you want. @guycalledfrank can probably confirm (or deny!).

**Comment by guycalledfrank** [comment]
In fact there's still a problem, because of this: https://github.com/playcanvas/engine/pull/1057/files#diff-a244156671d2beae826c3398f7d6fc21R195

Basically, each layer is split to opaque and transparent part (based on blendType), and
- on WebGL1 only the opaque part is rendered to the depth buffer (as separate pass).
- on WebGL2 depth grabbing occurs also after the opaque and before the transparent part (because transparent objects may already require depth - e.g. soft particles, water edges...)

On WebGL2 you would be able to get the desired behaviour by putting your blended objects into a separate layer between World (opaque) and Depth layers. It will write to the native ZBuffer, and get captured.

On WebGL1 however it's not as easy, because there's this separate pass...

Perhaps we can split to opaque/transparent by the depthWrite flag itself, instead of blendType. In this case it should be expected (and might be not obvious) that all blended objects with depthWrite = true won't be properly sorted.

**Comment by mvaligursky** [comment]
I'll close this ticket as suggested solution 'draw the HUD after the posteffect, what would be the proper options actually.' is already possible.
Please reopen if further work is needed.
