### ISSUE TITLE
Blend `normal` with opacity==1 and no opacityMap, should be blend as `none`.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#96]
If material blend is set to `normal` and `opacity` is 1.0 and there is no `opacityMap` set, it should blend it as `none` to prevent alpha sorting issues.

**Comment by guycalledfrank** [comment]
I'm not sure we need to change the blend for user. If I remember correctly, in the times of this issue, we were automatically changing the blend mode if opacity map is used. Currently you need to manually switch the blend from None to whatever, because you can use the map for alpha test. So if you then decide to remove map or change the slider, why should the blend change? It's an option you manually enabled, so you disable it back if needed.
